import type { Recipe } from './builder';

// WORLD 5 - IMPOSSIBLE (levels 81–100)
// Everything stacked: reverse + hidden + movers + multi-start + bombs +
// delays that nearly equal the tip timer. One mistake. Brutal clocks.

const P = (x: number, y: number) => ({ x, y });
const vpath = (x: number, y0: number, y1: number, speed = 0.22) => ({
  path: [
    { x, y: y0 },
    { x, y: y1 },
  ],
  speed,
});
const hpath = (y: number, x0: number, x1: number, speed = 0.22) => ({
  path: [
    { x: x0, y },
    { x: x1, y },
  ],
  speed,
});

export const world5: Recipe[] = [
  {
    name: 'Opening Salvo',
    layout: 'line',
    count: 10,
    types: {
      1: { type: 'delay', delayMs: 1000 },
      4: { type: 'explosive', radius: 0.18 },
      9: { type: 'timer', before: 3.2 },
    },
    hiddenEdges: [
      [2, 3],
      [5, 6],
      [7, 8],
    ],
    fakeEdges: [
      [0, 4],
      [0, 9],
      [1, 6],
      [2, 8],
      [3, 9],
    ],
    fakes: [
      { x: 0.5, y: 0.12 },
      { x: 0.5, y: 0.88 },
      { x: 0.3, y: 0.28, from: 2 },
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 6,
    intro: 'World 5. No tutorials. Delay, hidden gaps, blast, tip timer.',
    hints: [
      'Three hidden gaps on the spine.',
      'Fake long-cuts and grey stubs are noise.',
      'Tap left immediately.',
    ],
  },
  {
    name: 'Mirror Spine',
    layout: 'line',
    count: 9,
    allReverse: true,
    fakeEdges: [
      [8, 6],
      [7, 5],
      [6, 4],
      [5, 3],
      [4, 2],
      [8, 4],
      [7, 2],
    ],
    fakes: [
      { x: 0.5, y: 0.14 },
      { x: 0.5, y: 0.86 },
    ],
    starts: [8],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 5,
    hints: [
      'Pure reverse line.',
      'Skip-looking reverse stubs are fake.',
      'One tap: right-most.',
    ],
  },
  {
    name: 'Web of Lies',
    layout: 'custom',
    points: [
      P(0.5, 0.5),
      P(0.5, 0.06),
      P(0.84, 0.2),
      P(0.94, 0.52),
      P(0.72, 0.9),
      P(0.28, 0.9),
      P(0.06, 0.52),
      P(0.16, 0.2),
      P(0.5, 0.28),
      P(0.7, 0.5),
      P(0.3, 0.5),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [0, 3],
      [0, 4],
      [0, 5],
      [0, 6],
      [0, 7],
    ],
    decoy: [8, 9, 10],
    types: {
      0: { type: 'splitter' },
      8: { type: 'bomb' },
      9: { type: 'bomb' },
      10: { type: 'bomb' },
    },
    fakeEdges: [
      [0, 8],
      [0, 9],
      [0, 10],
      [2, 9],
      [6, 10],
    ],
    fakes: [
      { x: 0.35, y: 0.35 },
      { x: 0.65, y: 0.65 },
    ],
    maxTaps: 1,
    starts: [0],
    maxMistakes: 1,
    timeLimit: 2.4,
    par: 4,
    hints: [
      'Seven real arms; three inner bombs are fake-wired.',
      'Grey blobs are not starts.',
      'One tap: hub.',
    ],
  },
  {
    name: 'Double Blind',
    layout: 'custom',
    points: [
      P(0.08, 0.5),
      P(0.28, 0.5),
      P(0.5, 0.2),
      P(0.5, 0.8),
      P(0.72, 0.5),
      P(0.92, 0.5),
      P(0.5, 0.5),
    ],
    edges: [
      [0, 1],
      [1, 2],
      [2, 4],
      [4, 5],
    ],
    decoy: [6],
    types: { 1: { type: 'splitter' }, 4: { type: 'merger' }, 6: { type: 'bomb' } },
    hiddenEdges: [
      [1, 3],
      [3, 4],
    ],
    fakeEdges: [
      [1, 6],
      [6, 4],
      [2, 3],
      [0, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.2,
    par: 6,
    hints: [
      'Lower branch is fully hidden.',
      'Centre bomb corridor is fake.',
      'Tap far left.',
    ],
  },
  {
    name: 'Sprint Swarm',
    layout: 'line',
    count: 8,
    moving: {
      0: vpath(0.12, 0.16, 0.84, 0.28),
      2: vpath(0.34, 0.84, 0.16, 0.28),
      4: vpath(0.58, 0.16, 0.84, 0.28),
      5: vpath(0.7, 0.84, 0.16, 0.28),
      6: vpath(0.82, 0.16, 0.84, 0.26),
    },
    types: { 7: { type: 'timer', before: 2.5 } },
    fakeEdges: [
      [0, 4],
      [1, 7],
      [2, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 2.7,
    par: 5,
    hints: [
      'Start drifts hard; tip timer at 2.5s.',
      'Do not chase - fire the chain.',
      'Catch left now.',
    ],
  },
  {
    name: 'Twin Crown',
    layout: 'custom',
    points: [
      P(0.88, 0.1),
      P(0.58, 0.28),
      P(0.28, 0.1),
      P(0.5, 0.48),
      P(0.5, 0.7),
      P(0.26, 0.9),
      P(0.74, 0.9),
      P(0.12, 0.4),
    ],
    edges: [
      [0, 1],
      [2, 1],
      [1, 3],
      [3, 4],
      [4, 5],
      [4, 6],
    ],
    decoy: [7],
    types: { 1: { type: 'merger' }, 4: { type: 'splitter' }, 7: { type: 'bomb' } },
    fakes: [{ x: 0.88, y: 0.48, from: 3 }],
    fakeEdges: [
      [3, 7],
      [0, 3],
      [2, 7],
    ],
    starts: [0, 2],
    maxMistakes: 1,
    maxTaps: 2,
    timeLimit: 2.4,
    par: 5,
    hints: [
      'Two top feeds into a merge, then a bottom split.',
      'Side bomb and grey stub are traps.',
      'Tap both upper starts, fast.',
    ],
  },
  {
    name: 'Timed Ring',
    layout: 'circle',
    count: 10,
    order: [0, 3, 6, 9, 2, 5, 8, 1, 4, 7],
    types: {
      3: { type: 'delay', delayMs: 900 },
      6: { type: 'delay', delayMs: 800 },
      7: { type: 'timer', before: 3.5 },
    },
    hiddenEdges: [
      [9, 2],
      [5, 8],
      [4, 7],
    ],
    fakeEdges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [4, 5],
      [0, 5],
      [3, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.8,
    par: 7,
    hints: [
      'Scrambled ring with delays and hidden leaps.',
      'Neighbour arcs are fake.',
      'Tap top now.',
    ],
  },
  {
    name: 'Nested Bomb',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.2, 0.3),
      P(0.8, 0.3),
      P(0.08, 0.56),
      P(0.5, 0.56),
      P(0.92, 0.56),
      P(0.5, 0.86),
      P(0.5, 0.38),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [1, 4],
      [2, 5],
      [3, 6],
      [4, 6],
      [5, 6],
    ],
    decoy: [7],
    types: {
      0: { type: 'splitter' },
      1: { type: 'splitter' },
      6: { type: 'merger' },
      7: { type: 'bomb' },
    },
    fakes: [{ x: 0.32, y: 0.18 }],
    fakeEdges: [
      [2, 4],
      [0, 7],
      [7, 6],
      [2, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.2,
    par: 6,
    hints: [
      'Nested splits into a three-way merge.',
      'Cross-link and bomb corridor are fake.',
      'One tap: top.',
    ],
  },
  {
    name: 'Hair Trigger',
    layout: 'line',
    count: 8,
    starts: [0],
    maxTaps: 1,
    maxMistakes: 1,
    timeLimit: 2.3,
    types: {
      2: { type: 'delay', delayMs: 600 },
      7: { type: 'timer', before: 2.1 },
    },
    fakeEdges: [
      [0, 4],
      [0, 7],
      [1, 6],
    ],
    par: 3,
    hints: [
      'One tap, 2.3s, tip dies at 2.1s.',
      'Fake leaps will not help.',
      'Tap left the instant it loads.',
    ],
  },
  {
    name: 'Flood Gate',
    layout: 'custom',
    points: [
      P(0.06, 0.9),
      P(0.26, 0.9),
      P(0.5, 0.9),
      P(0.74, 0.9),
      P(0.94, 0.9),
      P(0.5, 0.58),
      P(0.5, 0.3),
      P(0.5, 0.06),
      P(0.28, 0.58),
      P(0.72, 0.58),
    ],
    edges: [
      [0, 5],
      [1, 5],
      [2, 5],
      [3, 5],
      [4, 5],
      [5, 6],
      [6, 7],
    ],
    decoy: [8, 9],
    types: { 8: { type: 'bomb' }, 9: { type: 'bomb' } },
    allReverse: true,
    fakeEdges: [
      [8, 5],
      [5, 9],
      [7, 8],
    ],
    starts: [7],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 6,
    hints: [
      'Start at the crown.',
      'Energy floods five bases against arrows.',
      'One tap: top centre.',
    ],
  },
  {
    name: 'Four Corners',
    layout: 'custom',
    points: [
      P(0.08, 0.14),
      P(0.08, 0.86),
      P(0.92, 0.14),
      P(0.92, 0.86),
      P(0.5, 0.5),
      P(0.5, 0.14),
      P(0.5, 0.86),
    ],
    edges: [
      [0, 4],
      [1, 4],
      [2, 4],
      [3, 4],
    ],
    decoy: [5, 6],
    types: { 4: { type: 'merger' }, 5: { type: 'bomb' }, 6: { type: 'bomb' } },
    moving: { 4: hpath(0.5, 0.28, 0.72, 0.14) },
    fakeEdges: [
      [5, 4],
      [4, 6],
      [0, 5],
    ],
    starts: [0, 1, 2, 3],
    maxMistakes: 1,
    maxTaps: 4,
    timeLimit: 2.4,
    par: 4,
    hints: [
      'Four corners into a drifting merge.',
      'Vertical bombs are fake-only.',
      'Tap all four corners, no hesitation.',
    ],
  },
  {
    name: 'Shortcut Thicket',
    layout: 'line',
    count: 11,
    fakeEdges: [
      [0, 3],
      [1, 4],
      [2, 5],
      [3, 6],
      [4, 7],
      [5, 8],
      [6, 9],
      [7, 10],
      [0, 10],
      [1, 8],
      [2, 9],
    ],
    fakes: [
      { x: 0.22, y: 0.14 },
      { x: 0.78, y: 0.86 },
      { x: 0.5, y: 0.28, from: 4 },
      { x: 0.5, y: 0.72, from: 7 },
    ],
    types: {
      2: { type: 'delay', delayMs: 800 },
      5: { type: 'delay', delayMs: 800 },
      8: { type: 'delay', delayMs: 700 },
      10: { type: 'timer', before: 3.8 },
    },
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 7,
    hints: [
      'A thicket of fake shortcuts.',
      'Real path is the plain sequential line.',
      'Tap left.',
    ],
  },
  {
    name: 'Chain Blast',
    layout: 'custom',
    points: [
      P(0.5, 0.5),
      P(0.26, 0.16),
      P(0.74, 0.16),
      P(0.9, 0.5),
      P(0.64, 0.88),
      P(0.36, 0.88),
      P(0.1, 0.5),
      P(0.5, 0.26),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [0, 3],
      [0, 4],
      [0, 5],
      [0, 6],
    ],
    decoy: [7],
    types: {
      0: { type: 'explosive', radius: 0.5 },
      3: { type: 'explosive', radius: 0.22 },
      6: { type: 'explosive', radius: 0.22 },
      7: { type: 'bomb' },
    },
    fakeEdges: [
      [0, 7],
      [1, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.5,
    par: 4,
    hints: [
      'Centre blast arms secondary blasts.',
      'Inner bomb is fake-wired.',
      'One tap: centre.',
    ],
  },
  {
    name: 'Invisible Agenda',
    layout: 'custom',
    points: [
      P(0.5, 0.04),
      P(0.16, 0.28),
      P(0.84, 0.28),
      P(0.16, 0.58),
      P(0.84, 0.58),
      P(0.5, 0.88),
      P(0.5, 0.42),
    ],
    edges: [
      [0, 1],
      [0, 2],
    ],
    decoy: [6],
    hiddenEdges: [
      [1, 3],
      [2, 4],
      [3, 5],
      [4, 5],
    ],
    types: { 0: { type: 'splitter' }, 5: { type: 'merger' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [1, 4],
      [2, 3],
      [0, 6],
      [6, 5],
      [0, 5],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.2,
    par: 6,
    hints: [
      'Only top arms are visible.',
      'Symmetric hidden paths feed the merge.',
      'One tap: top.',
    ],
  },
  {
    name: 'Pendulum Hell',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.5, 0.26),
      P(0.5, 0.48),
      P(0.5, 0.7),
      P(0.5, 0.92),
    ],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
    ],
    moving: {
      0: hpath(0.06, 0.28, 0.72, 0.12),
      1: hpath(0.26, 0.08, 0.92, 0.26),
      2: hpath(0.48, 0.92, 0.08, 0.26),
      3: hpath(0.7, 0.08, 0.92, 0.26),
    },
    types: { 4: { type: 'timer', before: 2.5 } },
    fakeEdges: [
      [0, 4],
      [1, 4],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 2.7,
    par: 5,
    hints: [
      'Even the start swings; middle three whip harder.',
      'Fake drops to the tip are lies.',
      'Catch the top link immediately.',
    ],
  },
  {
    name: 'Two-Faced Reverse',
    layout: 'custom',
    points: [
      P(0.1, 0.5),
      P(0.32, 0.5),
      P(0.56, 0.5),
      P(0.86, 0.5),
      P(0.5, 0.14),
      P(0.5, 0.86),
      P(0.7, 0.28),
      P(0.7, 0.72),
    ],
    edges: [
      [3, 2],
      [2, 1],
      [1, 0],
      [4, 1],
      [5, 1],
    ],
    decoy: [6, 7],
    types: { 6: { type: 'bomb' }, 7: { type: 'bomb' } },
    allReverse: true,
    fakeEdges: [
      [6, 2],
      [2, 7],
      [0, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 5,
    hints: [
      'Whole board runs reverse.',
      'Start where arrows finally point.',
      'One tap: far left.',
    ],
  },
  {
    name: 'Binary Crush',
    layout: 'custom',
    points: [
      P(0.5, 0.04),
      P(0.2, 0.2),
      P(0.8, 0.2),
      P(0.06, 0.42),
      P(0.36, 0.42),
      P(0.64, 0.42),
      P(0.94, 0.42),
      P(0.26, 0.66),
      P(0.74, 0.66),
      P(0.5, 0.9),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [1, 4],
      [2, 5],
      [2, 6],
      [3, 7],
      [4, 7],
      [5, 8],
      [6, 8],
      [7, 9],
      [8, 9],
    ],
    types: {
      0: { type: 'splitter' },
      1: { type: 'splitter' },
      2: { type: 'splitter' },
      4: { type: 'delay', delayMs: 1000 },
      7: { type: 'merger' },
      8: { type: 'merger' },
      9: { type: 'timer', before: 3.8 },
    },
    fakeEdges: [
      [0, 9],
      [1, 8],
      [2, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 4.2,
    par: 8,
    hints: [
      'Binary tree folds back through merges.',
      'Direct drop to the tip is fake.',
      'One tap: crown.',
    ],
  },
  {
    name: 'No Retry',
    layout: 'custom',
    points: [
      P(0.9, 0.08),
      P(0.6, 0.08),
      P(0.26, 0.08),
      P(0.36, 0.38),
      P(0.64, 0.38),
      P(0.5, 0.62),
      P(0.26, 0.88),
      P(0.74, 0.88),
      P(0.1, 0.38),
    ],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 5],
      [4, 5],
      [5, 6],
      [5, 7],
    ],
    decoy: [8],
    types: { 5: { type: 'merger' }, 8: { type: 'bomb' } },
    hiddenEdges: [[1, 4]],
    fakes: [{ x: 0.9, y: 0.38, from: 2 }],
    fakeEdges: [
      [2, 8],
      [8, 5],
      [0, 5],
    ],
    maxTaps: 1,
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.2,
    par: 6,
    hints: [
      'Top row right-to-left; a hidden drop feeds the merge.',
      'Bomb corridor and grey stub are traps.',
      'One tap: top-right.',
    ],
  },
  {
    name: 'Last Stand',
    layout: 'custom',
    points: [
      P(0.5, 0.04),
      P(0.16, 0.26),
      P(0.84, 0.26),
      P(0.5, 0.46),
      P(0.16, 0.68),
      P(0.84, 0.68),
      P(0.5, 0.92),
      P(0.5, 0.26),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [3, 4],
      [3, 5],
      [4, 6],
      [5, 6],
    ],
    decoy: [7],
    types: {
      0: { type: 'explosive', radius: 0.28 },
      3: { type: 'merger' },
      6: { type: 'merger' },
      5: { type: 'delay', delayMs: 1000 },
      7: { type: 'bomb' },
    },
    hiddenEdges: [[2, 3]],
    fakeEdges: [
      [0, 7],
      [7, 3],
      [0, 6],
      [1, 5],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.5,
    par: 7,
    hints: [
      'Blast opens both sides; right feed into first merge is hidden.',
      'Bomb corridor and tip skip are fake.',
      'One tap: top.',
    ],
  },
  {
    name: 'Unbreakable',
    layout: 'custom',
    points: [
      P(0.5, 0.03),
      P(0.16, 0.16),
      P(0.84, 0.16),
      P(0.06, 0.4),
      P(0.5, 0.34),
      P(0.94, 0.4),
      P(0.24, 0.62),
      P(0.76, 0.62),
      P(0.5, 0.8),
      P(0.5, 0.96),
      P(0.5, 0.16),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [1, 4],
      [2, 5],
      [3, 6],
      [4, 6],
      [5, 7],
      [6, 8],
      [7, 8],
      [8, 9],
    ],
    decoy: [10],
    types: {
      0: { type: 'explosive', radius: 0.26 },
      4: { type: 'merger' },
      6: { type: 'merger' },
      7: { type: 'merger' },
      8: { type: 'merger' },
      3: { type: 'delay', delayMs: 900 },
      9: { type: 'timer', before: 4.2 },
      10: { type: 'bomb' },
    },
    hiddenEdges: [
      [2, 4],
      [4, 7],
    ],
    fakeEdges: [
      [0, 8],
      [0, 10],
      [10, 4],
      [1, 7],
      [0, 9],
    ],
    moving: {
      0: hpath(0.03, 0.38, 0.62, 0.08),
    },
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 4.5,
    par: 9,
    intro: 'The finale. Drift blast, hide, delay, merge stack, tip timer. Don’t break the chain.',
    hints: [
      'Crown blast opens the weave; hidden arms complete the merges.',
      'Straight drops and the bomb stub are lies.',
      'Catch the drifting top - then survive.',
    ],
  },
];
