import type { Recipe } from './builder';

// WORLD 3 — SPLIT & MERGE (levels 41–60)
// Branching and merging links, now laced with bombs, fakes and hidden wiring.
// Merge links only fire once every real pulse lands — miscounting costs the run.

const P = (x: number, y: number) => ({ x, y });

export const world3: Recipe[] = [
  {
    name: 'The Fork',
    layout: 'tree',
    fakeEdges: [[1, 4]],
    starts: [0],
    timeLimit: 4.5,
    par: 5,
    intro: 'A splitter feeds two branches. One drawn branch is a lie.',
    hints: ['Both real branches must finish.', 'One diagonal wire is fake.', 'Tap the top link.'],
  },
  {
    name: 'The Meeting',
    layout: 'diamond',
    types: { 3: { type: 'merger' } },
    starts: [0],
    timeLimit: 4.5,
    par: 5,
    intro: 'A merge link only fires once every real pulse has arrived.',
    hints: ['Both sides feed the square link.', 'It waits for both, no shortcuts.', 'Tap the top link.'],
  },
  {
    name: 'False Support',
    layout: 'custom',
    points: [P(0.5, 0.12), P(0.24, 0.36), P(0.76, 0.36), P(0.5, 0.58), P(0.5, 0.76), P(0.5, 0.92)],
    edges: [[0, 1], [0, 2], [2, 3], [3, 4], [4, 5]],
    fakeEdges: [[1, 3]],
    types: { 3: { type: 'merger' } },
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    intro: 'One line into the merge link is fake — it counts real inputs only.',
    hints: ['The merge link shows real inputs needed.', 'The left line carries nothing.', 'Tap the top link.'],
  },
  {
    name: 'Double Fork',
    layout: 'custom',
    points: [P(0.5, 0.1), P(0.5, 0.3), P(0.26, 0.5), P(0.74, 0.5), P(0.14, 0.72), P(0.38, 0.72), P(0.62, 0.72), P(0.86, 0.72)],
    edges: [[0, 1], [1, 2], [1, 3], [2, 4], [2, 5], [3, 6], [3, 7]],
    types: { 1: { type: 'splitter' }, 2: { type: 'splitter' }, 3: { type: 'splitter' } },
    starts: [0],
    timeLimit: 5,
    par: 6,
    hints: ['Splits inside splits.', 'All four bottom links matter.', 'Tap the top link.'],
  },
  {
    name: 'Triple Merge',
    layout: 'custom',
    points: [P(0.5, 0.1), P(0.2, 0.38), P(0.5, 0.38), P(0.8, 0.38), P(0.5, 0.62), P(0.5, 0.86)],
    edges: [[0, 1], [0, 2], [0, 3], [1, 4], [2, 4], [3, 4], [4, 5]],
    types: { 0: { type: 'splitter' }, 4: { type: 'merger' } },
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    hints: ['Three lines feed one merge link.', 'It needs all three, no exceptions.', 'Tap the top link.'],
  },
  {
    name: 'Cross Roads',
    layout: 'custom',
    points: [P(0.15, 0.3), P(0.15, 0.7), P(0.5, 0.5), P(0.85, 0.3), P(0.85, 0.7)],
    edges: [[0, 2], [1, 2], [2, 3], [2, 4]],
    types: { 2: { type: 'merger' } },
    starts: [0, 1],
    maxTaps: 2,
    timeLimit: 3.2,
    par: 5,
    intro: 'Two starts, one merge link, a hard two-tap limit.',
    hints: ['Both left links must fire.', 'No room for a wrong tap.', 'Tap both left links quickly.'],
  },
  {
    name: 'Timing the Merge',
    layout: 'custom',
    points: [P(0.5, 0.1), P(0.2, 0.3), P(0.8, 0.3), P(0.2, 0.6), P(0.8, 0.55), P(0.5, 0.82)],
    edges: [[0, 1], [0, 2], [1, 3], [2, 4], [3, 5], [4, 5]],
    types: { 0: { type: 'splitter' }, 5: { type: 'merger' }, 1: { type: 'delay', delayMs: 700 } },
    starts: [0],
    timeLimit: 5,
    par: 7,
    hints: ['One branch is slower.', 'The merge link waits, but the clock does not.', 'Tap the top link.'],
  },
  {
    name: 'Branch and Bomb',
    layout: 'custom',
    points: [P(0.5, 0.12), P(0.28, 0.4), P(0.72, 0.4), P(0.28, 0.72), P(0.5, 0.9)],
    edges: [[0, 1], [1, 3], [3, 4]],
    fakeEdges: [[0, 2]],
    types: { 0: { type: 'splitter' }, 2: { type: 'bomb' } },
    starts: [0],
    timeLimit: 4,
    par: 5,
    intro: 'A splitter with a fake line to a bomb. The real branch is the safe one.',
    hints: ['The line to the bomb is fake.', 'Only the left branch is wired.', 'Tap the top link.'],
  },
  {
    name: 'Two Merges',
    layout: 'custom',
    points: [P(0.5, 0.08), P(0.24, 0.28), P(0.76, 0.28), P(0.5, 0.44), P(0.24, 0.64), P(0.76, 0.64), P(0.5, 0.82)],
    edges: [[0, 1], [0, 2], [1, 3], [2, 3], [3, 4], [3, 5], [4, 6], [5, 6]],
    types: { 0: { type: 'splitter' }, 3: { type: 'merger' }, 6: { type: 'merger' } },
    starts: [0],
    timeLimit: 5,
    par: 7,
    hints: ['Merge, split, merge again.', 'Every link is on the path.', 'Tap the top link.'],
  },
  {
    name: 'Pick a Path',
    layout: 'custom',
    points: [P(0.5, 0.1), P(0.22, 0.4), P(0.78, 0.4), P(0.5, 0.7)],
    edges: [[0, 1], [1, 3]],
    fakeEdges: [[0, 2], [2, 3]],
    decoy: [2],
    starts: [0],
    maxTaps: 1,
    timeLimit: 3,
    par: 4,
    intro: 'Two routes down, one fake. One tap only.',
    hints: ['The right route carries nothing.', 'Only the left route is wired.', 'One tap on the top link.'],
  },
  {
    name: 'Simultaneous',
    layout: 'custom',
    points: [P(0.16, 0.2), P(0.16, 0.8), P(0.5, 0.5), P(0.84, 0.5)],
    edges: [[0, 2], [1, 2], [2, 3]],
    types: { 2: { type: 'merger' } },
    starts: [0, 1],
    maxTaps: 2,
    timeLimit: 2.8,
    par: 4,
    intro: 'Both pulses must land close together, and the clock barely allows it.',
    hints: ['Two taps, back to back.', 'The merge link needs both.', 'Tap both left links immediately.'],
  },
  {
    name: 'Splitter Ring',
    layout: 'custom',
    points: [P(0.5, 0.5), P(0.5, 0.14), P(0.8, 0.3), P(0.8, 0.7), P(0.5, 0.86), P(0.2, 0.7), P(0.2, 0.3)],
    edges: [[0, 1], [0, 2], [0, 3], [0, 4], [0, 5], [0, 6]],
    types: { 0: { type: 'splitter' } },
    starts: [0],
    maxTaps: 1,
    timeLimit: 2.6,
    par: 4,
    hints: ['One centre, six arms.', 'A single tap lights all of them.', 'Tap the centre.'],
  },
  {
    name: 'Long Way Round',
    layout: 'custom',
    points: [P(0.5, 0.1), P(0.2, 0.25), P(0.8, 0.25), P(0.15, 0.55), P(0.85, 0.55), P(0.3, 0.8), P(0.7, 0.8), P(0.5, 0.92)],
    edges: [[0, 1], [0, 2], [1, 3], [2, 4], [3, 5], [4, 6], [5, 7], [6, 7]],
    types: { 0: { type: 'splitter' }, 7: { type: 'merger' } },
    starts: [0],
    timeLimit: 5.5,
    par: 8,
    hints: ['A wide loop back to one link.', 'Both long branches feed the bottom.', 'Tap the top link.'],
  },
  {
    name: 'Conditional',
    layout: 'custom',
    points: [P(0.3, 0.14), P(0.7, 0.14), P(0.5, 0.4), P(0.5, 0.64), P(0.5, 0.86)],
    edges: [[0, 2], [1, 2], [2, 3], [3, 4]],
    types: { 2: { type: 'merger' } },
    fakes: [{ x: 0.14, y: 0.5 }],
    starts: [0, 1],
    maxTaps: 2,
    timeLimit: 3,
    par: 5,
    hints: ['The merge link needs both top links.', 'The grey blob is a decoy.', 'Tap both top links.'],
  },
  {
    name: 'Delay Fork',
    layout: 'tree',
    types: { 1: { type: 'splitter' }, 2: { type: 'delay', delayMs: 900 } },
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    hints: ['One branch is slow.', 'Both still finish — barely.', 'Tap the top link.'],
  },
  {
    name: 'Explosive Merge',
    layout: 'custom',
    points: [P(0.5, 0.12), P(0.24, 0.4), P(0.76, 0.4), P(0.5, 0.66), P(0.5, 0.88)],
    edges: [[0, 1], [0, 2], [1, 3], [2, 3], [3, 4]],
    types: { 0: { type: 'explosive', radius: 0.32 }, 3: { type: 'merger' } },
    starts: [0],
    maxTaps: 1,
    timeLimit: 3,
    par: 5,
    hints: ['The blast lights both branches at once.', 'The merge link gets both pulses together.', 'One tap on the top link.'],
  },
  {
    name: 'Weave',
    layout: 'custom',
    points: [P(0.5, 0.08), P(0.2, 0.3), P(0.8, 0.3), P(0.5, 0.5), P(0.2, 0.7), P(0.8, 0.7), P(0.5, 0.9)],
    edges: [[0, 1], [0, 2], [1, 3], [3, 4], [3, 5], [4, 6], [5, 6]],
    types: { 0: { type: 'splitter' }, 3: { type: 'merger' }, 6: { type: 'merger' } },
    hiddenEdges: [[2, 3]],
    starts: [0],
    timeLimit: 6,
    par: 8,
    hints: ['One connection is hidden until energy runs through it.', 'It is still real.', 'Tap the top link.'],
  },
  {
    name: 'Three Starts',
    layout: 'custom',
    points: [P(0.15, 0.15), P(0.5, 0.12), P(0.85, 0.15), P(0.5, 0.45), P(0.5, 0.7), P(0.5, 0.9)],
    edges: [[0, 3], [1, 3], [2, 3], [3, 4], [4, 5]],
    types: { 3: { type: 'merger' } },
    starts: [0, 1, 2],
    maxTaps: 3,
    timeLimit: 3.4,
    par: 6,
    hints: ['Three links feed the merge.', 'Tap all three, no waste.', 'Top-left, top-middle, top-right.'],
  },
  {
    name: 'Relay',
    layout: 'custom',
    points: [P(0.15, 0.2), P(0.15, 0.5), P(0.4, 0.35), P(0.62, 0.35), P(0.85, 0.2), P(0.85, 0.5), P(0.62, 0.7), P(0.4, 0.85)],
    edges: [[0, 2], [1, 2], [2, 3], [3, 4], [3, 5], [3, 6], [6, 7]],
    types: { 2: { type: 'merger' }, 3: { type: 'splitter' } },
    starts: [0, 1],
    maxTaps: 2,
    timeLimit: 4,
    par: 7,
    hints: ['Two links merge, then one splits three ways.', 'Every link is on the path.', 'Tap both left links.'],
  },
  {
    name: 'Split & Merge — Gauntlet',
    layout: 'custom',
    points: [
      P(0.5, 0.06), P(0.22, 0.24), P(0.78, 0.24), P(0.5, 0.4),
      P(0.16, 0.6), P(0.5, 0.62), P(0.84, 0.6), P(0.5, 0.82), P(0.5, 0.95),
    ],
    edges: [[0, 1], [0, 2], [1, 3], [2, 3], [3, 4], [3, 5], [3, 6], [4, 7], [5, 7], [6, 7], [7, 8]],
    types: {
      0: { type: 'splitter' },
      3: { type: 'merger' },
      5: { type: 'delay', delayMs: 500 },
      7: { type: 'merger' },
    },
    starts: [0],
    timeLimit: 6,
    par: 10,
    intro: 'Split, merge, split wide, merge again. One tap does it all — barely in time.',
    hints: ['Trace it top to bottom.', 'Every link is on the path.', 'Tap the very top link.'],
  },
];
