import type { Recipe } from './builder';

// WORLD 4 - CHAOS (levels 61–80)
// Reverse chains, mostly-hidden spines, explosives, bomb starts,
// movers on hidden gaps, stacked delays under tip timers.

const P = (x: number, y: number) => ({ x, y });
const vpath = (x: number, y0: number, y1: number, speed = 0.2) => ({
  path: [
    { x, y: y0 },
    { x, y: y1 },
  ],
  speed,
});

export const world4: Recipe[] = [
  {
    name: 'Against Grain',
    layout: 'line',
    count: 8,
    allReverse: true,
    fakeEdges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [4, 5],
      [5, 6],
      [0, 3],
    ],
    fakes: [{ x: 0.5, y: 0.16 }, { x: 0.5, y: 0.84 }],
    starts: [7],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 5,
    intro: 'World 4: reverse links. Energy runs against the arrows. Start at the tip.',
    hints: [
      'Arrows lie - energy runs right to left.',
      'Forward-looking stubs are fake noise.',
      'One tap: right-most link.',
    ],
  },
  {
    name: 'Mostly Ghost',
    layout: 'line',
    count: 9,
    order: [0, 1],
    hiddenEdges: [
      [1, 2],
      [2, 3],
      [3, 4],
      [4, 5],
      [5, 6],
      [6, 7],
      [7, 8],
    ],
    fakeEdges: [
      [0, 4],
      [0, 8],
      [1, 6],
      [2, 7],
    ],
    fakes: [{ x: 0.72, y: 0.22 }, { x: 0.28, y: 0.78 }],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 6,
    intro: 'Almost the entire spine is invisible until energy proves it.',
    hints: [
      'Only the first pair shows a wire.',
      'Hidden spine continues to the end.',
      'Tap left.',
    ],
  },
  {
    name: 'Blast Relay',
    layout: 'line',
    count: 8,
    types: {
      0: { type: 'explosive', radius: 0.22 },
      2: { type: 'explosive', radius: 0.22 },
      4: { type: 'explosive', radius: 0.22 },
      6: { type: 'explosive', radius: 0.2 },
      7: { type: 'timer', before: 2.6 },
    },
    fakeEdges: [
      [0, 3],
      [1, 5],
      [0, 7],
    ],
    fakes: [
      { x: 0.5, y: 0.16 },
      { x: 0.5, y: 0.84 },
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 4,
    hints: [
      'Each blast triggers the next down the line.',
      'Grey stubs and skip chords are noise.',
      'One tap: far left.',
    ],
  },
  {
    name: 'No Slack',
    layout: 'line',
    count: 7,
    types: {
      2: { type: 'delay', delayMs: 900 },
      6: { type: 'timer', before: 2.4 },
    },
    fakeEdges: [
      [0, 3],
      [1, 5],
      [0, 6],
    ],
    maxTaps: 1,
    starts: [0],
    maxMistakes: 1,
    timeLimit: 2.6,
    par: 4,
    intro: 'One tap, a delay, a tip timer. Math barely closes.',
    hints: [
      'Fake leaps will not save time.',
      'Tip dies at 2.4s.',
      'Tap left now.',
    ],
  },
  {
    name: 'Chord Storm',
    layout: 'line',
    count: 8,
    fakeEdges: [
      [0, 2],
      [1, 3],
      [2, 4],
      [3, 5],
      [4, 6],
      [0, 4],
      [1, 6],
      [2, 7],
      [0, 5],
      [1, 7],
    ],
    fakes: [
      { x: 0.5, y: 0.12 },
      { x: 0.5, y: 0.88 },
      { x: 0.26, y: 0.28, from: 1 },
      { x: 0.74, y: 0.72, from: 5 },
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 5,
    hints: [
      'Almost every drawn chord is fake.',
      'Only sequential neighbours are real.',
      'One tap: left end.',
    ],
  },
  {
    name: 'Triple Stall Zig',
    layout: 'zig',
    count: 7,
    types: {
      1: { type: 'delay', delayMs: 1100 },
      3: { type: 'delay', delayMs: 1100 },
      5: { type: 'delay', delayMs: 1100 },
    },
    fakeEdges: [
      [0, 4],
      [2, 6],
      [0, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4.2,
    par: 7,
    hints: [
      'Every other link stalls over a second.',
      'Fake skips do not dodge delays.',
      'Start left immediately.',
    ],
  },
  {
    name: 'Reverse Flood',
    layout: 'custom',
    points: [
      P(0.14, 0.9),
      P(0.5, 0.64),
      P(0.86, 0.9),
      P(0.5, 0.36),
      P(0.5, 0.08),
      P(0.28, 0.5),
      P(0.72, 0.5),
    ],
    edges: [
      [0, 3],
      [1, 3],
      [2, 3],
      [3, 4],
    ],
    decoy: [5, 6],
    types: { 5: { type: 'bomb' }, 6: { type: 'bomb' } },
    allReverse: true,
    fakeEdges: [
      [5, 3],
      [3, 6],
      [4, 5],
    ],
    starts: [4],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 5,
    intro: 'Reverse hub floods three bases. Side bombs are fake-only.',
    hints: [
      'Start at the top tip.',
      'Energy runs down against arrows.',
      'One tap: top.',
    ],
  },
  {
    name: 'Ring Maze',
    layout: 'custom',
    points: [
      P(0.12, 0.12),
      P(0.5, 0.1),
      P(0.88, 0.12),
      P(0.9, 0.5),
      P(0.88, 0.88),
      P(0.5, 0.9),
      P(0.12, 0.88),
      P(0.1, 0.5),
      P(0.5, 0.5),
      P(0.28, 0.28),
    ],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [4, 5],
      [5, 6],
      [6, 7],
      [7, 0],
    ],
    decoy: [8, 9],
    types: { 8: { type: 'bomb' }, 9: { type: 'bomb' } },
    fakeEdges: [
      [1, 8],
      [3, 8],
      [5, 8],
      [7, 8],
      [0, 9],
      [2, 9],
      [4, 9],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 7,
    hints: [
      'Centre and inner bombs are fake-wired.',
      'Walk the outer ring only.',
      'Start top-left.',
    ],
  },
  {
    name: 'Ghost Movers',
    layout: 'line',
    count: 8,
    hiddenEdges: [
      [1, 2],
      [3, 4],
      [5, 6],
    ],
    moving: {
      0: vpath(0.12, 0.22, 0.78, 0.22),
      2: vpath(0.34, 0.18, 0.82, 0.24),
      4: vpath(0.58, 0.82, 0.18, 0.24),
      6: vpath(0.82, 0.18, 0.82, 0.2),
    },
    types: { 7: { type: 'timer', before: 3 } },
    fakeEdges: [
      [0, 5],
      [1, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.2,
    par: 6,
    hints: [
      'Hidden gaps plus whipping movers - start drifts.',
      'Tip timer at 3s.',
      'Catch the left link.',
    ],
  },
  {
    name: 'Hub Ring',
    layout: 'custom',
    points: [
      P(0.5, 0.5),
      P(0.5, 0.08),
      P(0.86, 0.24),
      P(0.92, 0.58),
      P(0.68, 0.9),
      P(0.32, 0.9),
      P(0.08, 0.58),
      P(0.14, 0.24),
      P(0.72, 0.5),
    ],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [4, 5],
      [5, 6],
      [6, 7],
      [0, 4],
      [0, 6],
    ],
    decoy: [8],
    types: { 0: { type: 'splitter' }, 8: { type: 'bomb' } },
    fakeEdges: [
      [0, 8],
      [2, 8],
      [3, 8],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 5,
    hints: [
      'Hub feeds a ring and shortcuts.',
      'Side bomb is fake-only.',
      'One tap: centre.',
    ],
  },
  {
    name: 'Climb Back',
    layout: 'custom',
    points: [
      P(0.16, 0.1),
      P(0.84, 0.1),
      P(0.5, 0.36),
      P(0.5, 0.62),
      P(0.5, 0.9),
      P(0.28, 0.5),
      P(0.72, 0.5),
    ],
    edges: [
      [3, 4],
      [2, 3],
      [0, 2],
      [1, 2],
    ],
    decoy: [5, 6],
    types: { 5: { type: 'bomb' }, 6: { type: 'bomb' } },
    allReverse: true,
    fakeEdges: [
      [5, 2],
      [2, 6],
      [4, 5],
    ],
    starts: [4],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 5,
    hints: [
      'Start at the bottom tip.',
      'Energy climbs and forks against arrows.',
      'One tap: bottom.',
    ],
  },
  {
    name: 'Fuse Race',
    layout: 'line',
    count: 7,
    types: {
      0: { type: 'explosive', radius: 0.2 },
      2: { type: 'explosive', radius: 0.2 },
      4: { type: 'explosive', radius: 0.2 },
      6: { type: 'timer', before: 2.2 },
    },
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.4,
    par: 4,
    hints: [
      'Blast cascade to a 2.2s tip.',
      'No second chances.',
      'Tap left instantly.',
    ],
  },
  {
    name: 'Five Crowns',
    layout: 'custom',
    points: [
      P(0.1, 0.14),
      P(0.9, 0.14),
      P(0.5, 0.14),
      P(0.5, 0.4),
      P(0.5, 0.64),
      P(0.5, 0.9),
      P(0.28, 0.14),
      P(0.72, 0.14),
    ],
    edges: [
      [2, 3],
      [3, 4],
      [4, 5],
    ],
    decoy: [0, 1, 6, 7],
    types: {
      0: { type: 'bomb' },
      1: { type: 'bomb' },
      6: { type: 'bomb' },
      7: { type: 'bomb' },
    },
    fakeEdges: [
      [0, 3],
      [1, 3],
      [6, 2],
      [7, 2],
      [0, 2],
      [1, 2],
    ],
    starts: [2],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.5,
    par: 4,
    intro: 'Five top seats. Four are bombs. Only the centre crown is live.',
    hints: [
      'Outer top links are bombs.',
      'Only the middle top starts the spine.',
      'One tap: centre top.',
    ],
  },
  {
    name: 'Live Mines',
    layout: 'line',
    count: 9,
    order: [0, 1, 2, 4, 5, 7, 8],
    types: { 3: { type: 'bomb' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [2, 3],
      [3, 4],
      [5, 6],
      [6, 7],
      [1, 6],
      [4, 3],
      [2, 6],
    ],
    moving: {
      0: vpath(0.12, 0.28, 0.72, 0.18),
      2: vpath(0.34, 0.24, 0.76, 0.2),
      5: vpath(0.68, 0.76, 0.24, 0.2),
    },
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 6,
    hints: [
      'Bombs sit on the row; real path jumps them.',
      'Fake wires into bombs - never follow those.',
      'Catch the drifting left start.',
    ],
  },
  {
    name: 'Photo Finish',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.2, 0.34),
      P(0.8, 0.34),
      P(0.5, 0.6),
      P(0.5, 0.9),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 3],
      [3, 4],
    ],
    types: {
      0: { type: 'splitter' },
      1: { type: 'delay', delayMs: 1200 },
      3: { type: 'merger' },
      4: { type: 'timer', before: 2.8 },
    },
    fakeEdges: [
      [0, 3],
      [0, 4],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3,
    par: 5,
    hints: [
      'Slow left arm; tip timer at 2.8s.',
      'Fake centre drops do nothing.',
      'Tap top immediately.',
    ],
  },
  {
    name: 'Half Blind Ring',
    layout: 'circle',
    count: 8,
    hiddenEdges: [
      [1, 2],
      [3, 4],
      [5, 6],
      [7, 0],
    ],
    fakeEdges: [
      [0, 2],
      [2, 4],
      [4, 6],
      [1, 4],
      [3, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 6,
    hints: [
      'Half the ring is hidden.',
      'Shown chords that skip are fake.',
      'Start at the top.',
    ],
  },
  {
    name: 'Reverse Circle',
    layout: 'circle',
    count: 9,
    allReverse: true,
    fakeEdges: [
      [8, 7],
      [7, 6],
      [5, 4],
      [3, 2],
      [1, 0],
      [8, 5],
    ],
    starts: [8],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.2,
    par: 6,
    hints: [
      'Ring runs backwards.',
      'Some reverse-looking stubs are fake.',
      'Start just left of top (last in order).',
    ],
  },
  {
    name: 'Kitchen Sink',
    layout: 'custom',
    points: [
      P(0.5, 0.04),
      P(0.18, 0.26),
      P(0.82, 0.26),
      P(0.18, 0.54),
      P(0.82, 0.54),
      P(0.5, 0.74),
      P(0.5, 0.94),
      P(0.5, 0.4),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 4],
      [3, 5],
      [4, 5],
      [5, 6],
    ],
    decoy: [7],
    types: {
      0: { type: 'explosive', radius: 0.28 },
      3: { type: 'delay', delayMs: 1000 },
      5: { type: 'merger' },
      6: { type: 'timer', before: 3.2 },
      7: { type: 'bomb' },
    },
    fakeEdges: [
      [0, 5],
      [0, 7],
      [7, 5],
      [0, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.5,
    par: 7,
    hints: [
      'Blast, slow arm, merge, tip timer.',
      'Straight bomb path is a lie.',
      'One tap: top.',
    ],
  },
  {
    name: 'Sealed Split',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.2, 0.34),
      P(0.8, 0.34),
      P(0.5, 0.56),
      P(0.26, 0.84),
      P(0.74, 0.84),
      P(0.5, 0.34),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 3],
      [3, 4],
      [3, 5],
    ],
    decoy: [6],
    types: { 0: { type: 'splitter' }, 3: { type: 'merger' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [0, 6],
      [6, 3],
      [0, 4],
    ],
    maxTaps: 1,
    starts: [0],
    maxMistakes: 1,
    timeLimit: 2.8,
    par: 5,
    hints: [
      'Split, merge, split again.',
      'Centre bomb corridor is fake.',
      'One tap: top.',
    ],
  },
  {
    name: 'Chaos - Final',
    layout: 'custom',
    points: [
      P(0.9, 0.08),
      P(0.64, 0.08),
      P(0.34, 0.08),
      P(0.5, 0.34),
      P(0.2, 0.56),
      P(0.8, 0.56),
      P(0.5, 0.78),
      P(0.5, 0.94),
      P(0.1, 0.34),
    ],
    edges: [
      [0, 1],
      [1, 2],
      [3, 4],
      [3, 5],
      [4, 6],
      [5, 6],
      [6, 7],
    ],
    decoy: [8],
    types: {
      3: { type: 'splitter' },
      4: { type: 'delay', delayMs: 1000 },
      6: { type: 'merger' },
      7: { type: 'timer', before: 3.5 },
      8: { type: 'bomb' },
    },
    fakes: [{ x: 0.9, y: 0.4 }],
    hiddenEdges: [[2, 3]],
    fakeEdges: [
      [0, 8],
      [8, 3],
      [2, 5],
      [0, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.8,
    par: 8,
    intro: 'Right-to-left open, hidden drop, split, delay, merge, tip timer.',
    hints: [
      'Top row runs right to left.',
      'Hidden link drops into the splitter.',
      'One tap: top-right, immediately.',
    ],
  },
];
