import type { Recipe } from './builder';

// WORLD 2 — MOVING LINKS (levels 21–40)
// Drifting links, obstacles, reverse chains and a first merge link — all under
// a clock that only gets meaner.

const P = (x: number, y: number) => ({ x, y });
const vp = (x: number, y0: number, y1: number, speed = 0.14) => ({ path: [P(x, y0), P(x, y1)], speed });
const hp = (y: number, x0: number, x1: number, speed = 0.14) => ({ path: [P(x0, y), P(x1, y)], speed });

export const world2: Recipe[] = [
  {
    name: 'Full Sprint',
    layout: 'line',
    count: 5,
    moving: { 2: vp(0.5, 0.28, 0.72, 0.2) },
    starts: [0],
    maxTaps: 1,
    timeLimit: 3,
    par: 4,
    intro: 'World 2: links move now, and the clock does not care.',
    hints: ['Aim for the link, not the spot.', 'The wiring never changes.', 'Tap the far-left link immediately.'],
  },
  {
    name: 'Crosscut',
    layout: 'line',
    count: 6,
    moving: { 2: vp(0.42, 0.28, 0.72), 4: vp(0.72, 0.72, 0.28) },
    fakeEdges: [[0, 3], [1, 5]],
    starts: [0],
    timeLimit: 4,
    par: 6,
    hints: ['Two movers cross paths.', 'The diagonal wires are fake.', 'Start left, watch the flow only.'],
  },
  {
    name: 'Wobble Ring',
    layout: 'circle',
    count: 7,
    order: [0, 3, 6, 2, 5, 1, 4],
    moving: { 2: hp(0.7, 0.62, 0.78), 5: hp(0.7, 0.38, 0.22) },
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    hints: ['The ring wobbles but the order does not change.', 'Trust the arrows.', 'Start at the top link.'],
  },
  {
    name: 'Trapdoor',
    layout: 'dual',
    count: 8,
    decoy: [4, 5, 6, 7],
    types: { 5: { type: 'bomb' } },
    moving: { 1: vp(0.386, 0.24, 0.44) },
    starts: [0],
    timeLimit: 4,
    par: 5,
    intro: 'The bottom chain hides a bomb mid-row.',
    hints: ['Only the top chain is real.', 'Never explore the bottom row.', 'Start top-left.'],
  },
  {
    name: 'Roadblock',
    layout: 'line',
    count: 6,
    fakes: [{ x: 0.5, y: 0.5 }],
    types: { 5: { type: 'bomb' } },
    order: [0, 1, 2, 3, 4],
    starts: [0],
    timeLimit: 3.5,
    par: 5,
    intro: 'An obstacle blocks the middle; a bomb waits at the far end, unwired.',
    hints: ['The grey blob is not a link — ignore it.', 'The bomb has no real wire to it.', 'Start at the left.'],
  },
  {
    name: 'Photo Finish',
    layout: 'line',
    count: 5,
    moving: { 3: vp(0.66, 0.28, 0.72, 0.24) },
    starts: [0],
    maxTaps: 1,
    timeLimit: 2.6,
    par: 4,
    intro: 'Barely enough time to breathe.',
    hints: ['No room for a second look.', 'The chain is a straight line.', 'Tap left the instant it loads.'],
  },
  {
    name: 'Sliding Grid',
    layout: 'grid',
    count: 9,
    cols: 3,
    rows: 3,
    moving: { 3: hp(0.5, 0.16, 0.5), 5: hp(0.5, 0.84, 0.5) },
    fakeEdges: [[0, 4], [2, 6]],
    starts: [0],
    timeLimit: 5.5,
    par: 7,
    hints: ['Two rows slide sideways.', 'Diagonal shortcuts are fake.', 'Start top-left, snake through.'],
  },
  {
    name: 'Loose Zigzag',
    layout: 'zig',
    count: 6,
    moving: { 1: vp(0.29, 0.24, 0.44), 4: vp(0.66, 0.56, 0.76) },
    hiddenEdges: [[2, 3]],
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    hints: ['One join in the middle is invisible.', 'It is still real.', 'Start at the left end.'],
  },
  {
    name: 'Whirlpool',
    layout: 'spiral',
    count: 7,
    order: [0, 1, 2, 3, 4, 5],
    moving: { 3: hp(0.5, 0.4, 0.6) },
    types: { 6: { type: 'bomb' } },
    fakeEdges: [[4, 6]],
    starts: [0],
    timeLimit: 5,
    par: 6,
    intro: 'The spiral pulls inward toward a bomb at its core, wired only by a lie.',
    hints: ['The centre bomb has no real feed.', 'Follow the spiral, stop before the core.', 'Start on the outer end.'],
  },
  {
    name: 'Dead Reckoning',
    layout: 'line',
    count: 6,
    types: { 5: { type: 'timer', before: 3 } },
    moving: { 2: vp(0.42, 0.28, 0.72) },
    starts: [0],
    par: 5,
    intro: 'A moving link and a hard 3-second deadline, together.',
    hints: ['The last link expires at 3s.', 'Do not hesitate on the mover.', 'Start left immediately.'],
  },
  {
    name: 'Double Current',
    layout: 'custom',
    points: [P(0.16, 0.16), P(0.16, 0.84), P(0.5, 0.5), P(0.84, 0.3), P(0.84, 0.7)],
    edges: [[0, 2], [1, 2], [2, 3], [2, 4]],
    types: { 2: { type: 'merger' } },
    moving: { 2: hp(0.5, 0.42, 0.58, 0.1) },
    starts: [0, 1],
    timeLimit: 3.6,
    par: 5,
    intro: 'Your first merge link — it only fires once both sides land, and it drifts.',
    hints: ['Two taps needed, both left links.', 'The merge link needs both pulses.', 'Tap both corners fast.'],
  },
  {
    name: 'Breathing Ring',
    layout: 'circle',
    count: 8,
    order: [0, 2, 4, 6, 1, 3, 5, 7],
    moving: { 2: hp(0.5, 0.84, 0.72), 6: hp(0.5, 0.16, 0.28) },
    starts: [0],
    timeLimit: 5,
    par: 7,
    hints: ['The ring pulses but never rewires.', 'Every other seat is the real order.', 'Start at the top.'],
  },
  {
    name: 'Molasses',
    layout: 'line',
    count: 6,
    types: { 2: { type: 'delay', delayMs: 900 } },
    moving: { 4: vp(0.72, 0.28, 0.72) },
    fakes: [{ x: 0.28, y: 0.22, from: 1 }],
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    hints: ['One link stalls almost a second.', 'The grey stub is a dead end.', 'Start left without delay.'],
  },
  {
    name: 'Rolling Charge',
    layout: 'star',
    count: 6,
    types: { 0: { type: 'explosive', radius: 0.4 } },
    moving: { 0: hp(0.5, 0.42, 0.58, 0.08) },
    starts: [0],
    maxTaps: 1,
    timeLimit: 3,
    par: 4,
    intro: 'A moving explosive link. Its blast still reaches everything wired.',
    hints: ['The centre drifts and detonates.', 'The blast still covers the ring.', 'One tap on the centre.'],
  },
  {
    name: 'Tight Leash',
    layout: 'zig',
    count: 6,
    moving: { 2: vp(0.44, 0.24, 0.5), 3: vp(0.56, 0.5, 0.76) },
    starts: [0],
    maxTaps: 2,
    timeLimit: 4,
    par: 6,
    hints: ['Only two taps allowed total.', 'The start alone runs everything.', 'Tap the left end once.'],
  },
  {
    name: 'Swarm',
    layout: 'line',
    count: 6,
    moving: {
      1: vp(0.27, 0.28, 0.72),
      2: vp(0.42, 0.72, 0.28),
      3: vp(0.57, 0.28, 0.72),
      4: vp(0.72, 0.72, 0.28),
    },
    starts: [0],
    timeLimit: 5,
    par: 7,
    hints: ['Four links weave at once.', 'The order underneath never changes.', 'Start left.'],
  },
  {
    name: 'Impostor',
    layout: 'line',
    count: 5,
    order: [0, 1, 2, 3],
    fakes: [{ x: 0.5, y: 0.5, from: 2 }],
    moving: { 3: vp(0.66, 0.28, 0.72) },
    types: { 4: { type: 'bomb' } },
    fakeEdges: [[3, 4]],
    starts: [0],
    timeLimit: 3.5,
    par: 5,
    intro: 'A fake link and a bomb, both dressed up as real branches.',
    hints: ['Two branches are traps.', 'One is a dead grey stub, one hides a bomb.', 'Run the straight line from the left.'],
  },
  {
    name: 'Backwards Drift',
    layout: 'line',
    count: 6,
    allReverse: true,
    moving: { 2: vp(0.42, 0.28, 0.72) },
    types: { 2: { type: 'reverse' } },
    starts: [5],
    timeLimit: 4.5,
    par: 6,
    intro: 'Energy now runs backward against the drawn arrows — and one link still moves.',
    hints: ['Right to left this time.', 'The mover does not change the wiring.', 'Tap the right-most link.'],
  },
  {
    name: 'Minefield',
    layout: 'zig',
    count: 7,
    order: [0, 1, 2, 3, 4, 6],
    types: { 5: { type: 'bomb' } },
    moving: { 3: vp(0.54, 0.5, 0.28) },
    fakeEdges: [[2, 5]],
    starts: [0],
    timeLimit: 5,
    par: 7,
    intro: 'A bomb and a mover share the same row.',
    hints: ['The bomb has no real feed into it.', 'Stay on the zig.', 'Start at the left end.'],
  },
  {
    name: 'Moving Links — Gauntlet',
    layout: 'line',
    count: 7,
    allReverse: true,
    moving: { 3: vp(0.5, 0.26, 0.74) },
    types: { 3: { type: 'reverse' } },
    fakes: [{ x: 0.5, y: 0.06 }],
    starts: [6],
    timeLimit: 4.4,
    par: 7,
    intro: 'Reverse flow and a drifting link, on the shortest World 2 clock yet.',
    hints: ['Right to left, against the arrows.', 'The mover does not change the wiring.', 'Tap the right-most link.'],
  },
];
