import type { Recipe } from './builder';

// WORLD 4 — CHAOS (levels 61–80)
// Fake links, hidden links, explosive links, timers, one-tap limits and
// reversed chains — stacked two and three at a time.

const P = (x: number, y: number) => ({ x, y });
const vp = (x: number, y0: number, y1: number, speed = 0.15) => ({ path: [P(x, y0), P(x, y1)], speed });

export const world4: Recipe[] = [
  {
    name: 'Backwards',
    layout: 'line',
    count: 5,
    allReverse: true,
    fakeEdges: [[2, 0]],
    starts: [4],
    timeLimit: 3.5,
    par: 5,
    intro: 'World 4: reverse links. Energy flows against the arrows — start at the arrowhead.',
    hints: ['The arrows lie about direction.', 'Energy runs right to left here.', 'Tap the right-most link.'],
  },
  {
    name: 'Blind Faith',
    layout: 'line',
    count: 6,
    order: [0, 1, 2],
    hiddenEdges: [[2, 3], [3, 4], [4, 5]],
    fakes: [{ x: 0.5, y: 0.2, from: 1 }],
    starts: [0],
    timeLimit: 5,
    par: 6,
    intro: 'Hidden links do not show until energy runs through them.',
    hints: ['Half the chain is invisible.', 'It connects the two visible groups.', 'Tap the left-most link.'],
  },
  {
    name: 'Chain Reaction',
    layout: 'line',
    count: 6,
    types: {
      0: { type: 'explosive', radius: 0.24 },
      2: { type: 'explosive', radius: 0.24 },
      4: { type: 'explosive', radius: 0.24 },
    },
    starts: [0],
    maxTaps: 1,
    timeLimit: 3,
    par: 4,
    hints: ['Each blast triggers the next.', 'One tap sets off the cascade.', 'Tap the left-most link.'],
  },
  {
    name: 'Pressure',
    layout: 'line',
    count: 6,
    types: { 5: { type: 'timer', before: 3 } },
    maxTaps: 1,
    starts: [0],
    par: 4,
    intro: 'One tap, three-second timer. No margin at all.',
    hints: ['One tap, three seconds.', 'The start runs the whole line.', 'Tap the left-most link right now.'],
  },
  {
    name: 'Hall of Mirrors',
    layout: 'line',
    count: 5,
    fakeEdges: [[1, 3], [2, 4], [0, 2]],
    fakes: [{ x: 0.5, y: 0.2 }, { x: 0.5, y: 0.8 }],
    starts: [0],
    timeLimit: 3.5,
    par: 5,
    hints: ['Most of these connections are fake.', 'Follow only the solid straight line.', 'Tap the left-most link.'],
  },
  {
    name: 'Slow Burn',
    layout: 'zig',
    count: 6,
    types: {
      1: { type: 'delay', delayMs: 700 },
      3: { type: 'delay', delayMs: 700 },
      5: { type: 'delay', delayMs: 700 },
    },
    starts: [0],
    timeLimit: 5,
    par: 7,
    hints: ['Every other link stalls briefly.', 'It still all connects.', 'Tap the left end.'],
  },
  {
    name: 'Reverse Split',
    layout: 'custom',
    points: [P(0.2, 0.85), P(0.5, 0.6), P(0.8, 0.85), P(0.5, 0.35), P(0.5, 0.12)],
    edges: [[0, 3], [1, 3], [2, 3], [3, 4]],
    allReverse: true,
    starts: [4],
    timeLimit: 4,
    par: 6,
    intro: 'A reverse link that spreads energy back to three links at once.',
    hints: ['Start at the top.', 'Energy flows downward against the arrows.', 'Tap the top link.'],
  },
  {
    name: 'The Maze',
    layout: 'custom',
    points: [
      P(0.16, 0.16), P(0.5, 0.14), P(0.84, 0.16), P(0.86, 0.5),
      P(0.84, 0.84), P(0.5, 0.86), P(0.16, 0.84), P(0.14, 0.5), P(0.5, 0.5),
    ],
    edges: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]],
    fakeEdges: [[1, 8], [3, 8], [5, 8], [7, 8]],
    types: { 8: { type: 'bomb' } },
    starts: [0],
    timeLimit: 5.5,
    par: 7,
    intro: 'A bomb owns the centre; every line touching it is fake.',
    hints: ['The centre link is a bomb.', 'Every line touching it is fake.', 'Follow the ring around the edge.'],
  },
  {
    name: 'Ghost Runner',
    layout: 'line',
    count: 6,
    hiddenEdges: [[1, 2], [3, 4]],
    moving: { 2: vp(0.416, 0.28, 0.72), 4: vp(0.72, 0.72, 0.28) },
    starts: [0],
    timeLimit: 5,
    par: 7,
    hints: ['Hidden links and moving links together.', 'Trust the line.', 'Tap the left end.'],
  },
  {
    name: 'One Tap, Many Links',
    layout: 'custom',
    points: [
      P(0.5, 0.5), P(0.5, 0.12), P(0.85, 0.28), P(0.88, 0.62), P(0.62, 0.88),
      P(0.38, 0.88), P(0.12, 0.62), P(0.15, 0.28),
    ],
    edges: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [0, 4], [0, 6]],
    types: { 0: { type: 'splitter' } },
    starts: [0],
    maxTaps: 1,
    timeLimit: 3.4,
    par: 5,
    hints: ['The centre feeds a loop.', 'One tap lights the whole ring.', 'Tap the centre link.'],
  },
  {
    name: 'Backwards Merge',
    layout: 'custom',
    points: [P(0.2, 0.15), P(0.8, 0.15), P(0.5, 0.4), P(0.5, 0.65), P(0.5, 0.9)],
    edges: [[3, 4], [2, 3], [0, 2], [1, 2]],
    allReverse: true,
    starts: [4],
    timeLimit: 4,
    par: 6,
    hints: ['Start at the bottom.', 'Energy climbs against the arrows and splits.', 'Tap the bottom link.'],
  },
  {
    name: 'Countdown Cascade',
    layout: 'line',
    count: 6,
    types: {
      0: { type: 'explosive', radius: 0.22 },
      2: { type: 'explosive', radius: 0.22 },
      4: { type: 'explosive', radius: 0.22 },
      5: { type: 'timer', before: 2.6 },
    },
    starts: [0],
    maxTaps: 1,
    par: 4,
    hints: ['Blasts chain to the timer link.', 'Do it fast, no second tap.', 'Tap the left-most link immediately.'],
  },
  {
    name: 'Decoy Starts',
    layout: 'custom',
    points: [P(0.15, 0.2), P(0.85, 0.2), P(0.5, 0.2), P(0.5, 0.45), P(0.5, 0.68), P(0.5, 0.9)],
    edges: [[2, 3], [3, 4], [4, 5]],
    decoy: [0, 1],
    starts: [2],
    maxTaps: 1,
    timeLimit: 3.4,
    par: 5,
    intro: 'Three links sit at the top. Only the middle one is wired.',
    hints: ['The outer top links go nowhere.', 'Only the centre top link starts the chain.', 'Tap the middle top link.'],
  },
  {
    name: 'Live Ordnance',
    layout: 'line',
    count: 5,
    order: [0, 1, 2, 4],
    types: { 3: { type: 'bomb' } },
    starts: [0],
    timeLimit: 3.5,
    par: 5,
    hints: ['One link on the row is a bomb.', 'The chain skips it.', 'Tap the left end and watch the arrows.'],
  },
  {
    name: 'Split Finish',
    layout: 'custom',
    points: [P(0.5, 0.1), P(0.25, 0.4), P(0.75, 0.4), P(0.5, 0.7), P(0.5, 0.9)],
    edges: [[0, 1], [0, 2], [1, 3], [2, 3], [3, 4]],
    types: { 0: { type: 'splitter' }, 1: { type: 'delay', delayMs: 700 }, 3: { type: 'merger' }, 4: { type: 'timer', before: 3.4 } },
    starts: [0],
    par: 6,
    hints: ['One branch drags, the finish link counts down.', 'The merge still catches up — barely.', 'Tap the top link right away.'],
  },
  {
    name: 'Invisible Ring',
    layout: 'circle',
    count: 7,
    order: [0, 1, 2, 3, 4, 5, 6],
    hiddenEdges: [[1, 2], [3, 4], [5, 6]],
    starts: [0],
    timeLimit: 5,
    par: 7,
    hints: ['Parts of the ring are hidden.', 'It is a full loop.', 'Start at the top link.'],
  },
  {
    name: 'Reverse Ring',
    layout: 'circle',
    count: 7,
    order: [0, 1, 2, 3, 4, 5, 6],
    allReverse: true,
    starts: [6],
    timeLimit: 5,
    par: 7,
    hints: ['The ring runs backwards.', 'Start where the last arrow points.', 'Tap the link left of the top.'],
  },
  {
    name: 'Everything at Once',
    layout: 'custom',
    points: [P(0.5, 0.08), P(0.22, 0.3), P(0.78, 0.3), P(0.22, 0.58), P(0.78, 0.58), P(0.5, 0.8), P(0.5, 0.95)],
    edges: [[0, 1], [0, 2], [1, 3], [2, 4], [3, 5], [4, 5], [5, 6]],
    fakeEdges: [[0, 5]],
    types: {
      0: { type: 'explosive', radius: 0.3 },
      3: { type: 'delay', delayMs: 600 },
      5: { type: 'merger' },
      6: { type: 'timer', before: 4.2 },
    },
    starts: [0],
    par: 6,
    hints: ['Blast, split, one slow branch, merge, beat the timer.', 'The straight-down line is fake.', 'Tap the top link.'],
  },
  {
    name: 'Locked In',
    layout: 'custom',
    points: [P(0.5, 0.1), P(0.25, 0.38), P(0.75, 0.38), P(0.5, 0.62), P(0.3, 0.86), P(0.7, 0.86)],
    edges: [[0, 1], [0, 2], [1, 3], [2, 3], [3, 4], [3, 5]],
    types: { 0: { type: 'splitter' }, 3: { type: 'merger' } },
    maxTaps: 1,
    starts: [0],
    timeLimit: 3.2,
    par: 5,
    hints: ['Split then merge then split.', 'One tap only.', 'Tap the top link.'],
  },
  {
    name: 'Chaos — Gauntlet',
    layout: 'custom',
    points: [
      P(0.85, 0.12), P(0.6, 0.12), P(0.35, 0.12), P(0.5, 0.4),
      P(0.25, 0.62), P(0.75, 0.62), P(0.5, 0.85), P(0.5, 0.97),
    ],
    edges: [[0, 1], [1, 2], [3, 4], [3, 5], [4, 6], [5, 6], [6, 7]],
    types: {
      3: { type: 'splitter' },
      4: { type: 'delay', delayMs: 500 },
      6: { type: 'merger' },
      7: { type: 'timer', before: 4.4 },
    },
    fakes: [{ x: 0.15, y: 0.4 }],
    hiddenEdges: [[2, 3]],
    starts: [0],
    par: 8,
    intro: 'Reversed opening arrows, a hidden link, a split, a delay, a merge and a timer.',
    hints: ['The top row runs right to left.', 'Then a hidden link drops into the split.', 'Tap the top-right link.'],
  },
];
