import type { Recipe } from './builder';

// WORLD 1 — FIRST LINK (levels 1–20)
// No mercy from level one: bombs, fake wires, scrambled order and a clock are
// all live immediately. One wrong tap ends the run everywhere.

const P = (x: number, y: number) => ({ x, y });

export const world1: Recipe[] = [
  {
    name: 'First Blood',
    layout: 'custom',
    points: [P(0.12, 0.5), P(0.34, 0.5), P(0.56, 0.5), P(0.78, 0.5), P(0.12, 0.22)],
    edges: [[0, 1], [1, 2], [2, 3]],
    fakeEdges: [[0, 4]],
    types: { 4: { type: 'bomb' } },
    starts: [0],
    par: 4,
    intro: 'A bomb sits right beside the real start. Read the arrows, not the layout.',
    hints: [
      'The stub above the first link is a bomb — never tap it.',
      'Only the straight row carries energy.',
      'Tap the far-left link on the middle row.',
    ],
  },
  {
    name: 'Triple Bait',
    layout: 'line',
    count: 9,
    order: [2, 3, 4, 5],
    edges: [[0, 1], [6, 7], [7, 8]],
    decoy: [0, 1, 6, 7, 8],
    starts: [2],
    par: 5,
    intro: 'Three clusters look identical. Only the middle one runs end to end.',
    hints: ['Outer clusters dead-end fast.', 'Count from the left — the third link is real.', 'Tap the 3rd link from the left.'],
  },
  {
    name: 'Down or Bust',
    layout: 'vert',
    count: 6,
    fakeEdges: [[3, 2], [4, 3], [1, 0]],
    starts: [0],
    par: 5,
    intro: 'Some drawn wires point the wrong way and carry nothing.',
    hints: ['Upward arrows are all fake.', 'Real flow is strictly top to bottom.', 'Start at the very top.'],
  },
  {
    name: 'Ring Jump',
    layout: 'circle',
    count: 8,
    order: [0, 3, 6, 1, 4, 7, 2, 5],
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    intro: 'A ring where neighbours are never connected. Follow arrows only.',
    hints: ['Close arcs are not wired.', 'Energy always jumps 3 seats.', 'Start at the top link.'],
  },
  {
    name: 'No Hesitation',
    layout: 'line',
    count: 6,
    fakeEdges: [[0, 3], [1, 5], [0, 5]],
    starts: [0],
    maxTaps: 1,
    timeLimit: 3,
    par: 4,
    intro: 'One tap, one chance, a short clock. Commit instantly.',
    hints: ['Long chords are lies.', 'Only the sequential row is real.', 'Tap the left-most link now.'],
  },
  {
    name: 'Ghost Wire',
    layout: 'line',
    count: 6,
    order: [0, 1, 2],
    hiddenEdges: [[2, 3]],
    edges: [[3, 4], [4, 5]],
    fakes: [{ x: 0.5, y: 0.22, from: 1 }],
    starts: [0],
    par: 6,
    intro: 'A real link can be invisible until energy runs through it.',
    hints: ['The grey stub goes nowhere.', 'A hidden wire bridges the gap at the middle.', 'Start at the far left.'],
  },
  {
    name: 'Poison Path',
    layout: 'dual',
    count: 8,
    decoy: [4, 5, 6, 7],
    types: { 4: { type: 'bomb' }, 6: { type: 'bomb' } },
    starts: [0],
    timeLimit: 4.5,
    par: 5,
    intro: 'Two chains. The lower one is laced with bombs.',
    hints: ['Never touch the bottom row.', 'Only the top chain matters.', 'Start top-left.'],
  },
  {
    name: 'Twin Ignition',
    layout: 'line',
    count: 6,
    order: [0, 1, 2],
    edges: [[3, 4], [4, 5]],
    starts: [0, 3],
    timeLimit: 3.5,
    par: 5,
    intro: 'Two live starts, both required, one short clock.',
    hints: ['Two beginnings — tap both.', 'Left-most of each half.', 'Do it fast, back to back.'],
  },
  {
    name: 'Stall Tax',
    layout: 'line',
    count: 6,
    types: { 2: { type: 'delay', delayMs: 1000 } },
    fakeEdges: [[0, 3], [1, 5]],
    starts: [0],
    timeLimit: 4,
    par: 6,
    intro: 'A delay link burns a full second of your clock. Plan for it.',
    hints: ['The 3rd link stalls on purpose.', 'Fake skips do not save time.', 'Start immediately, far left.'],
  },
  {
    name: 'Chase',
    layout: 'line',
    count: 6,
    moving: {
      2: { path: [P(0.4, 0.26), P(0.4, 0.74)], speed: 0.16 },
      4: { path: [P(0.72, 0.74), P(0.72, 0.26)], speed: 0.16 },
    },
    starts: [0],
    timeLimit: 4,
    par: 5,
    intro: 'Two links sprint back and forth. The chain still finds them.',
    hints: ['Do not chase them with your eyes.', 'The wiring never changes.', 'Start left, right away.'],
  },
  {
    name: 'Buried Start',
    layout: 'zig',
    count: 7,
    order: [3, 2, 1, 0, 4, 5, 6],
    starts: [3],
    timeLimit: 5,
    par: 6,
    intro: 'The true start is not at either end. Trace arrows backward to find it.',
    hints: ['Follow arrows to their source.', 'It sits just right of centre.', 'Tap the 4th link from the left.'],
  },
  {
    name: 'False Valley',
    layout: 'vshape',
    count: 7,
    fakeEdges: [[0, 6], [1, 5], [2, 4]],
    starts: [0],
    timeLimit: 5,
    par: 6,
    intro: 'Cross chords over the valley all lie.',
    hints: ['Nothing crosses the V.', 'Follow the two slopes only.', 'Start at the top-left tip.'],
  },
  {
    name: 'One Arm Bandit',
    layout: 'star',
    count: 6,
    types: { 0: { type: 'splitter' } },
    fakeEdges: [[0, 5]],
    starts: [0],
    maxTaps: 1,
    timeLimit: 4,
    par: 4,
    intro: 'A splitter fires every real arm at once — but one wire here is fake.',
    hints: ['One arm is unwired despite the drawing.', 'The rest still fire together.', 'One tap on the centre.'],
  },
  {
    name: 'Snake Pit',
    layout: 'grid',
    count: 9,
    cols: 3,
    rows: 3,
    order: [0, 1, 2, 3, 5, 6, 7, 8],
    fakeEdges: [[0, 4], [2, 7], [5, 6]],
    types: { 4: { type: 'bomb' } },
    starts: [0],
    timeLimit: 5.5,
    par: 6,
    intro: 'A bomb sits in the centre. Fake shortcuts try to lure energy toward it.',
    hints: ['Nothing real touches the centre.', 'The path snakes the outside only.', 'Start top-left.'],
  },
  {
    name: 'Leapfrog',
    layout: 'circle',
    count: 8,
    order: [0, 3, 6, 1, 4, 7, 2, 5],
    fakeEdges: [[0, 1], [4, 5]],
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    hints: ['Adjacent seats are fake.', 'Trust only the arrows.', 'Start at the top.'],
  },
  {
    name: 'Bomb Row',
    layout: 'line',
    count: 9,
    order: [0, 1, 2, 3, 5, 6, 8],
    types: { 4: { type: 'bomb' }, 7: { type: 'bomb' } },
    starts: [0],
    timeLimit: 4.5,
    par: 6,
    intro: 'Two bombs sit directly in the row. The wiring steps around them.',
    hints: ['Bombs at positions 5 and 8.', 'The path hops each one.', 'Start at the far left.'],
  },
  {
    name: 'Blast Radius',
    layout: 'custom',
    points: [P(0.5, 0.5), P(0.32, 0.32), P(0.68, 0.32), P(0.32, 0.68), P(0.68, 0.68), P(0.5, 0.06)],
    edges: [[4, 5]],
    types: { 0: { type: 'explosive', radius: 0.3 } },
    starts: [0],
    maxTaps: 1,
    timeLimit: 3.5,
    par: 4,
    intro: 'The blast covers the inner ring; the far link only lights by wire.',
    hints: ['Four inner links catch the blast.', 'One of them still has to pass it on.', 'One tap on the centre.'],
  },
  {
    name: 'Countdown',
    layout: 'line',
    count: 7,
    types: { 6: { type: 'timer', before: 2.6 } },
    fakeEdges: [[0, 4]],
    starts: [0],
    par: 5,
    intro: 'This link has its own private countdown — 2.6 seconds, no exceptions.',
    hints: ['The last link dies at 2.6s.', 'The whole row has to make it in time.', 'Tap the first link immediately.'],
  },
  {
    name: 'Single Spark',
    layout: 'line',
    count: 7,
    order: [2, 3, 4, 5, 6],
    edges: [[0, 1]],
    decoy: [0, 1],
    starts: [2],
    maxTaps: 1,
    timeLimit: 3.5,
    par: 4,
    intro: 'One tap only, and the real start is not the obvious one.',
    hints: ['The left pair is a decoy.', 'Count three links in.', 'Tap the 3rd link from the left.'],
  },
  {
    name: 'First Link — Gauntlet',
    layout: 'zig',
    count: 9,
    order: [4, 3, 2, 1, 0, 5, 6, 7, 8],
    types: { 6: { type: 'delay', delayMs: 650 } },
    fakes: [{ x: 0.5, y: 0.08, from: 5 }],
    moving: { 2: { path: [P(0.36, 0.26), P(0.36, 0.68)], speed: 0.13 } },
    starts: [4],
    timeLimit: 6,
    par: 8,
    intro: 'A hidden start, a fake stub, a mover and a delay — all at once.',
    hints: ['The start sits mid-zig, not at an end.', 'Trace arrows backward to find it.', 'Tap the 5th link from the left.'],
  },
];
