import type { Recipe } from './builder';

// WORLD 1 - FIRST LINK (levels 1–20)
// Teach every core lie early: bomb starts, fake wires, scrambled rings,
// dual taps, delays, movers, timers. maxMistakes 1 and clocks already sting.

const P = (x: number, y: number) => ({ x, y });

export const world1: Recipe[] = [
  {
    name: 'Hot Wire',
    layout: 'custom',
    points: [P(0.14, 0.5), P(0.36, 0.5), P(0.58, 0.5), P(0.8, 0.5), P(0.14, 0.26), P(0.14, 0.74)],
    edges: [
      [0, 1],
      [1, 2],
      [2, 3],
    ],
    fakeEdges: [
      [4, 0],
      [5, 0],
      [0, 4],
    ],
    types: { 4: { type: 'bomb' }, 5: { type: 'bomb' } },
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.2,
    par: 4,
    intro: 'Two bombs hug the real start. One wrong tap ends the run.',
    hints: [
      'Side stubs next to the left link are bombs.',
      'Only the middle row carries energy.',
      'One tap: left-most middle link.',
    ],
  },
  {
    name: 'Three Lies',
    layout: 'line',
    count: 11,
    order: [3, 4, 5, 6],
    edges: [
      [0, 1],
      [1, 2],
      [7, 8],
      [9, 10],
    ],
    decoy: [0, 1, 2, 7, 8, 9, 10],
    types: { 0: { type: 'bomb' }, 7: { type: 'bomb' }, 9: { type: 'bomb' } },
    fakeEdges: [
      [2, 3],
      [6, 7],
    ],
    starts: [3],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3,
    par: 4,
    intro: 'Four clusters. Three open on bombs. One mid chain is live.',
    hints: [
      'Outer clusters are bait.',
      'The live spine sits between the bomb packs.',
      'Tap the fourth link from the left.',
    ],
  },
  {
    name: 'Arrow Fiction',
    layout: 'vert',
    count: 6,
    fakeEdges: [
      [5, 4],
      [4, 3],
      [3, 2],
      [2, 1],
      [1, 0],
      [5, 2],
    ],
    fakes: [{ x: 0.28, y: 0.42, from: 2 }, { x: 0.72, y: 0.58, from: 3 }],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 5,
    intro: 'Upward drawings look helpful. They carry nothing.',
    hints: [
      'Every upward stub is fake.',
      'Grey branches die instantly.',
      'Start at the top and trust the down spine.',
    ],
  },
  {
    name: 'Scrambled Ring',
    layout: 'circle',
    count: 8,
    order: [0, 3, 6, 1, 4, 7, 2, 5],
    fakeEdges: [
      [0, 1],
      [1, 2],
      [2, 3],
      [4, 5],
      [6, 7],
      [7, 0],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 6,
    intro: 'Neighbours on the ring are not connected. Leap.',
    hints: [
      'Close arcs are almost all fake.',
      'Energy jumps every other seat.',
      'Start at the top.',
    ],
  },
  {
    name: 'No Hesitation',
    layout: 'line',
    count: 6,
    fakeEdges: [
      [0, 2],
      [1, 4],
      [0, 5],
      [2, 5],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.5,
    par: 3,
    intro: 'Clock is the enemy. Fake shortcuts save nothing.',
    hints: [
      'Long chords are lies.',
      'Sequential line only.',
      'Tap left the instant it loads.',
    ],
  },
  {
    name: 'Ghost Bridge',
    layout: 'line',
    count: 8,
    order: [0, 1, 2],
    hiddenEdges: [[2, 3]],
    edges: [
      [3, 4],
      [4, 5],
      [5, 6],
      [6, 7],
    ],
    fakeEdges: [
      [1, 5],
      [0, 4],
      [2, 6],
    ],
    fakes: [
      { x: 0.4, y: 0.18, from: 1 },
      { x: 0.68, y: 0.82, from: 4 },
      { x: 0.18, y: 0.78 },
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 6,
    intro: 'The gap mid-row is real but invisible.',
    hints: [
      'Grey stubs are traps.',
      'A hidden wire joins the two halves.',
      'Start far left.',
    ],
  },
  {
    name: 'Lower Death',
    layout: 'dual',
    count: 8,
    decoy: [4, 5, 6, 7],
    types: { 4: { type: 'bomb' }, 5: { type: 'bomb' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [0, 4],
      [1, 5],
      [2, 6],
      [3, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 4,
    intro: 'Bottom row is a bomb gallery. Cross wires are fake.',
    hints: [
      'Never tap the lower row.',
      'Cross links into bombs carry nothing.',
      'One tap: top-left.',
    ],
  },
  {
    name: 'Twin Fuse',
    layout: 'line',
    count: 9,
    order: [0, 1, 2],
    edges: [
      [4, 5],
      [5, 6],
    ],
    decoy: [3, 7, 8],
    types: { 3: { type: 'bomb' }, 7: { type: 'bomb' }, 8: { type: 'bomb' } },
    fakeEdges: [
      [2, 3],
      [3, 4],
      [6, 7],
      [2, 8],
    ],
    starts: [0, 4],
    maxMistakes: 1,
    maxTaps: 2,
    timeLimit: 2.6,
    par: 4,
    intro: 'Two live starts. Bombs sit between and beside them.',
    hints: [
      'Bombs separate the two short chains.',
      'Exactly two taps - both true starts.',
      'Left-most of each live trio.',
    ],
  },
  {
    name: 'Taxed',
    layout: 'line',
    count: 6,
    types: {
      1: { type: 'delay', delayMs: 1100 },
      3: { type: 'delay', delayMs: 1000 },
    },
    fakeEdges: [
      [0, 2],
      [0, 4],
      [1, 5],
    ],
    fakes: [{ x: 0.5, y: 0.2, from: 2 }],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 5,
    intro: 'Delays eat most of the clock. Start yesterday.',
    hints: [
      'Two delays burn over two seconds.',
      'Fake skips do not dodge stalls.',
      'Tap left immediately.',
    ],
  },
  {
    name: 'Crossing Guard',
    layout: 'line',
    count: 7,
    moving: {
      1: {
        path: [P(0.26, 0.18), P(0.26, 0.82)],
        speed: 0.22,
      },
      3: {
        path: [P(0.5, 0.82), P(0.5, 0.18)],
        speed: 0.22,
      },
    },
    types: { 6: { type: 'timer', before: 2.8 } },
    fakeEdges: [
      [0, 3],
      [2, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3,
    par: 5,
    intro: 'Movers whip across the start lane. Tip timer will not wait.',
    hints: [
      'Do not chase the movers.',
      'Tip dies at 2.8s.',
      'Tap left the instant you can.',
    ],
  },
  {
    name: 'Buried Source',
    layout: 'zig',
    count: 9,
    order: [4, 3, 2, 1, 0, 5, 6, 7, 8],
    fakeEdges: [
      [0, 1],
      [8, 7],
      [0, 8],
      [2, 6],
    ],
    fakes: [{ x: 0.1, y: 0.5 }, { x: 0.9, y: 0.5 }],
    starts: [4],
    maxMistakes: 1,
    timeLimit: 4,
    par: 7,
    intro: 'Ends look like starts. The source is mid-zig.',
    hints: [
      'Trace arrows backward.',
      'End caps are mid-chain, not sources.',
      'Tap the middle of the zig.',
    ],
  },
  {
    name: 'Valley Trap',
    layout: 'vshape',
    count: 7,
    fakeEdges: [
      [0, 6],
      [1, 5],
      [2, 4],
      [0, 3],
    ],
    fakes: [
      { x: 0.5, y: 0.14, from: 2 },
      { x: 0.5, y: 0.9, from: 4 },
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 5,
    hints: [
      'Cross chords across the V are fake.',
      'Grey stubs off the valley kill focus.',
      'Start at the upper-left tip.',
    ],
  },
  {
    name: 'Bad Arms',
    layout: 'custom',
    points: [
      P(0.5, 0.5),
      P(0.5, 0.12),
      P(0.84, 0.3),
      P(0.84, 0.7),
      P(0.5, 0.9),
      P(0.16, 0.7),
      P(0.16, 0.3),
      P(0.68, 0.5),
      P(0.32, 0.5),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [0, 4],
      [0, 5],
      [0, 6],
    ],
    fakeEdges: [
      [0, 3],
      [0, 7],
      [0, 8],
    ],
    types: {
      0: { type: 'splitter' },
      3: { type: 'bomb' },
      7: { type: 'bomb' },
      8: { type: 'bomb' },
    },
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 4,
    intro: 'Splitter fires every real arm - never the bomb stubs.',
    hints: [
      'Three bomb arms ride fake wires.',
      'Five real tips must light.',
      'One tap on the hub.',
    ],
  },
  {
    name: 'Snake Lie',
    layout: 'grid',
    count: 9,
    cols: 3,
    rows: 3,
    order: [0, 1, 2, 5, 4, 3, 6, 7, 8],
    fakeEdges: [
      [0, 3],
      [0, 4],
      [1, 7],
      [2, 8],
      [2, 4],
      [4, 8],
      [3, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4.2,
    par: 6,
    hints: [
      'Grid shortcuts are almost all fake.',
      'Snake the rows; reverse the middle.',
      'Start top-left.',
    ],
  },
  {
    name: 'Leap Four',
    layout: 'circle',
    count: 9,
    order: [0, 4, 8, 3, 7, 2, 6, 1, 5],
    fakeEdges: [
      [0, 1],
      [1, 2],
      [3, 4],
      [4, 5],
      [6, 7],
      [8, 0],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4.5,
    par: 7,
    hints: [
      'Positions lie; leap by fours.',
      'Neighbour arcs are bait.',
      'Start at the top.',
    ],
  },
  {
    name: 'Skip Mines',
    layout: 'line',
    count: 9,
    order: [0, 1, 2, 4, 5, 7, 8],
    types: { 3: { type: 'bomb' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [2, 3],
      [3, 4],
      [5, 6],
      [6, 7],
      [1, 6],
      [4, 3],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.8,
    par: 6,
    intro: 'Bombs sit on the row. Real arrows skip them; fakes do not.',
    hints: [
      'Fourth and seventh seats are bombs.',
      'Follow only the skip path.',
      'Start far left.',
    ],
  },
  {
    name: 'Shockwave',
    layout: 'custom',
    points: [
      P(0.5, 0.5),
      P(0.3, 0.28),
      P(0.7, 0.28),
      P(0.3, 0.72),
      P(0.7, 0.72),
      P(0.5, 0.08),
      P(0.5, 0.92),
      P(0.08, 0.5),
      P(0.92, 0.5),
    ],
    edges: [
      [1, 5],
      [4, 6],
    ],
    fakeEdges: [
      [0, 7],
      [0, 8],
    ],
    types: {
      0: { type: 'explosive', radius: 0.34 },
      7: { type: 'bomb' },
      8: { type: 'bomb' },
    },
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3,
    par: 4,
    intro: 'Blast covers the diamond. Far tips need wired exits; side bombs are fake.',
    hints: [
      'Blast lights the four diamond seats.',
      'Top and bottom tips need hand-offs.',
      'One tap: centre. Never the side bombs.',
    ],
  },
  {
    name: 'Budget Zero',
    layout: 'line',
    count: 7,
    types: {
      2: { type: 'delay', delayMs: 900 },
      6: { type: 'timer', before: 2.5 },
    },
    fakeEdges: [
      [0, 3],
      [1, 5],
      [0, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 2.8,
    par: 4,
    intro: 'Delay plus tip timer. The math barely closes.',
    hints: [
      'Tip dies at 2.5s.',
      'One delay eats nearly a second.',
      'Tap left now.',
    ],
  },
  {
    name: 'Crowd Control',
    layout: 'custom',
    points: [
      P(0.1, 0.28),
      P(0.1, 0.5),
      P(0.1, 0.72),
      P(0.32, 0.5),
      P(0.52, 0.5),
      P(0.72, 0.5),
      P(0.9, 0.5),
      P(0.32, 0.22),
      P(0.32, 0.78),
    ],
    edges: [
      [3, 4],
      [4, 5],
      [5, 6],
    ],
    fakeEdges: [
      [0, 3],
      [1, 3],
      [2, 3],
      [7, 3],
      [8, 3],
    ],
    decoy: [0, 1, 2, 7, 8],
    types: {
      0: { type: 'bomb' },
      1: { type: 'bomb' },
      2: { type: 'bomb' },
      7: { type: 'bomb' },
    },
    starts: [3],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.6,
    par: 4,
    intro: 'A bomb crowd surrounds the real source. One tap.',
    hints: [
      'Left cluster is almost all bombs.',
      'Real chain begins just right of that cluster.',
      'Tap the first filled middle link.',
    ],
  },
  {
    name: 'First Link - Final',
    layout: 'zig',
    count: 10,
    order: [5, 4, 3, 2, 1, 0, 6, 7, 8, 9],
    types: {
      3: { type: 'delay', delayMs: 1000 },
      8: { type: 'timer', before: 3.5 },
    },
    moving: {
      2: { path: [P(0.3, 0.22), P(0.3, 0.72)], speed: 0.18 },
      7: { path: [P(0.72, 0.72), P(0.72, 0.22)], speed: 0.18 },
    },
    fakeEdges: [
      [0, 9],
      [2, 7],
      [1, 8],
    ],
    fakes: [{ x: 0.5, y: 0.08, from: 6 }, { x: 0.5, y: 0.92 }],
    starts: [5],
    maxMistakes: 1,
    timeLimit: 4,
    par: 7,
    intro: 'Hidden start, movers, delay, timer, fakes - World 1 boss.',
    hints: [
      'Source is mid-zig; ends are not starts.',
      'Ignore grey stubs and long fake cuts.',
      'Tap the sixth link from the left, immediately.',
    ],
  },
];
