import type { Recipe } from './builder';

// WORLD 3 - SPLIT & MERGE (levels 41–60)
// Miswired merges, bomb arms on fake wires, dual/triple starts with
// maxTaps = starts.length, delays that starve the tip timer.

const P = (x: number, y: number) => ({ x, y });

export const world3: Recipe[] = [
  {
    name: 'False Fork',
    layout: 'tree',
    types: { 1: { type: 'splitter' } },
    fakeEdges: [
      [0, 4],
      [0, 5],
      [0, 2],
      [1, 5],
    ],
    fakes: [{ x: 0.5, y: 0.95 }, { x: 0.72, y: 0.2 }],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 4,
    intro: 'World 3: both branches required. Fake chords look faster.',
    hints: [
      'Skip chords that jump the splitter.',
      'Both lower arms must light.',
      'One tap: top.',
    ],
  },
  {
    name: 'Counted Merge',
    layout: 'diamond',
    types: {
      3: { type: 'merger' },
      1: { type: 'delay', delayMs: 900 },
    },
    fakeEdges: [
      [0, 3],
      [0, 5],
      [1, 4],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 5,
    intro: 'Merge waits for every real input. Fake shortcuts change nothing.',
    hints: [
      'Straight-down wire into the merge is fake.',
      'Both side arms still required.',
      'Tap the top.',
    ],
  },
  {
    name: 'Phantom Support',
    layout: 'diamond',
    types: { 3: { type: 'merger' } },
    fakeEdges: [
      [1, 3],
      [0, 5],
      [2, 5],
      [0, 4],
    ],
    fakes: [{ x: 0.12, y: 0.58 }, { x: 0.88, y: 0.58 }],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.2,
    par: 5,
    intro: 'One drawn support into the merge is fake - count solid inputs only.',
    hints: [
      'Left inbound to the merge is fake.',
      'Merge still needs the right arm.',
      'Tap top and trust the counter.',
    ],
  },
  {
    name: 'Quad Tip',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.5, 0.26),
      P(0.26, 0.46),
      P(0.74, 0.46),
      P(0.12, 0.7),
      P(0.38, 0.7),
      P(0.62, 0.7),
      P(0.88, 0.7),
      P(0.5, 0.92),
    ],
    edges: [
      [0, 1],
      [1, 2],
      [1, 3],
      [2, 4],
      [2, 5],
      [3, 6],
      [3, 7],
    ],
    decoy: [8],
    types: {
      1: { type: 'splitter' },
      2: { type: 'splitter' },
      3: { type: 'splitter' },
      8: { type: 'bomb' },
    },
    fakeEdges: [
      [1, 8],
      [4, 8],
      [7, 8],
      [0, 8],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 3.2,
    par: 5,
    hints: [
      'Splits inside splits - four tips matter.',
      'Bottom bomb is only on fake wires.',
      'One tap: top.',
    ],
  },
  {
    name: 'Three Into One',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.16, 0.34),
      P(0.5, 0.34),
      P(0.84, 0.34),
      P(0.5, 0.62),
      P(0.5, 0.88),
      P(0.5, 0.2),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [0, 3],
      [1, 4],
      [2, 4],
      [3, 4],
      [4, 5],
    ],
    decoy: [6],
    types: { 0: { type: 'splitter' }, 4: { type: 'merger' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [0, 6],
      [6, 4],
      [0, 5],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.2,
    par: 5,
    hints: [
      'Three real arms into one merge.',
      'Centre bomb stub is decorative death.',
      'Tap the top splitter.',
    ],
  },
  {
    name: 'Side Feed',
    layout: 'custom',
    points: [
      P(0.1, 0.2),
      P(0.1, 0.8),
      P(0.5, 0.5),
      P(0.9, 0.2),
      P(0.9, 0.8),
      P(0.5, 0.1),
      P(0.5, 0.9),
    ],
    edges: [
      [0, 2],
      [1, 2],
      [2, 3],
      [2, 4],
    ],
    decoy: [5, 6],
    types: { 2: { type: 'merger' }, 5: { type: 'bomb' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [5, 2],
      [2, 6],
      [0, 5],
    ],
    starts: [0, 1],
    maxMistakes: 1,
    maxTaps: 2,
    timeLimit: 2.4,
    par: 4,
    intro: 'Two starts feed the merge. Vertical bombs are fake-wired only.',
    hints: [
      'Top/bottom bombs are not real inputs.',
      'Both left starts, two taps.',
      'Tap upper-left then lower-left.',
    ],
  },
  {
    name: 'Late Arm',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.16, 0.28),
      P(0.84, 0.28),
      P(0.16, 0.56),
      P(0.84, 0.5),
      P(0.5, 0.78),
      P(0.5, 0.94),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 4],
      [3, 5],
      [4, 5],
      [5, 6],
    ],
    types: {
      0: { type: 'splitter' },
      1: { type: 'delay', delayMs: 1300 },
      5: { type: 'merger' },
      6: { type: 'timer', before: 3.2 },
    },
    fakeEdges: [
      [0, 5],
      [0, 6],
      [2, 5],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.5,
    par: 6,
    hints: [
      'Left branch is slow; merge waits.',
      'Straight fakes into merge/tip do nothing.',
      'Tap top immediately.',
    ],
  },
  {
    name: 'Bomb Tree',
    layout: 'custom',
    points: [
      P(0.5, 0.08),
      P(0.22, 0.36),
      P(0.78, 0.36),
      P(0.22, 0.66),
      P(0.5, 0.88),
      P(0.78, 0.66),
    ],
    edges: [
      [0, 1],
      [1, 3],
      [3, 4],
    ],
    fakeEdges: [
      [0, 2],
      [2, 5],
      [5, 4],
      [0, 5],
    ],
    types: { 0: { type: 'splitter' }, 2: { type: 'bomb' }, 5: { type: 'bomb' } },
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 4,
    intro: 'Right tree is pure bomb theatre on fake wires.',
    hints: [
      'Only the left cascade is wired.',
      'Right bombs never receive real energy.',
      'One tap: top.',
    ],
  },
  {
    name: 'Cascade Merges',
    layout: 'custom',
    points: [
      P(0.5, 0.04),
      P(0.2, 0.24),
      P(0.8, 0.24),
      P(0.5, 0.4),
      P(0.2, 0.6),
      P(0.8, 0.6),
      P(0.5, 0.78),
      P(0.5, 0.94),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 3],
      [3, 4],
      [3, 5],
      [4, 6],
      [5, 6],
      [6, 7],
    ],
    types: {
      0: { type: 'splitter' },
      3: { type: 'merger' },
      6: { type: 'merger' },
      4: { type: 'delay', delayMs: 1000 },
    },
    fakeEdges: [
      [0, 6],
      [0, 7],
      [1, 5],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 7,
    hints: [
      'Merge, split, merge, tip.',
      'Skip long fake drops.',
      'Tap the top.',
    ],
  },
  {
    name: 'One True Path',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.18, 0.34),
      P(0.82, 0.34),
      P(0.5, 0.62),
      P(0.5, 0.88),
      P(0.32, 0.48),
      P(0.68, 0.48),
    ],
    edges: [
      [0, 1],
      [1, 3],
      [3, 4],
    ],
    fakeEdges: [
      [0, 2],
      [2, 3],
      [0, 5],
      [5, 6],
      [6, 4],
      [2, 4],
    ],
    decoy: [2, 5, 6],
    types: { 2: { type: 'bomb' } },
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 4,
    hints: [
      'Right route and middle weave are decoys.',
      'Only left cascade is real.',
      'One tap: top.',
    ],
  },
  {
    name: 'Instant Pair',
    layout: 'custom',
    points: [
      P(0.12, 0.16),
      P(0.12, 0.84),
      P(0.5, 0.5),
      P(0.88, 0.5),
      P(0.5, 0.16),
      P(0.5, 0.84),
    ],
    edges: [
      [0, 2],
      [1, 2],
      [2, 3],
    ],
    decoy: [4, 5],
    types: { 2: { type: 'merger' }, 4: { type: 'bomb' }, 5: { type: 'bomb' } },
    fakeEdges: [
      [4, 2],
      [2, 5],
    ],
    starts: [0, 1],
    maxMistakes: 1,
    maxTaps: 2,
    timeLimit: 2.2,
    par: 3,
    intro: 'Merge needs both pulses inside a brutal window.',
    hints: [
      'Vertical bombs are fake-wired only.',
      'Two left starts, 2.2 seconds.',
      'Double-tap both left links now.',
    ],
  },
  {
    name: 'Seven Arms',
    layout: 'custom',
    points: [
      P(0.5, 0.5),
      P(0.5, 0.1),
      P(0.82, 0.26),
      P(0.9, 0.6),
      P(0.64, 0.9),
      P(0.36, 0.9),
      P(0.1, 0.6),
      P(0.18, 0.26),
      P(0.5, 0.3),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [0, 3],
      [0, 4],
      [0, 5],
      [0, 6],
      [0, 7],
    ],
    decoy: [8],
    types: { 0: { type: 'splitter' }, 8: { type: 'bomb' } },
    fakeEdges: [
      [0, 8],
      [1, 8],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.5,
    par: 4,
    hints: [
      'Seven arms, one fake inner bomb.',
      'Single centre tap.',
      'Tap the hub.',
    ],
  },
  {
    name: 'Wide Loop',
    layout: 'custom',
    points: [
      P(0.5, 0.06),
      P(0.16, 0.22),
      P(0.84, 0.22),
      P(0.1, 0.48),
      P(0.9, 0.48),
      P(0.26, 0.74),
      P(0.74, 0.74),
      P(0.5, 0.92),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 4],
      [3, 5],
      [4, 6],
      [5, 7],
      [6, 7],
    ],
    types: {
      0: { type: 'splitter' },
      3: { type: 'delay', delayMs: 1100 },
      7: { type: 'merger' },
    },
    fakeEdges: [
      [0, 7],
      [1, 6],
      [2, 5],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 7,
    hints: [
      'Wide loop; delay on the left arc.',
      'Direct drop to the merge is fake.',
      'Tap top.',
    ],
  },
  {
    name: 'Crown Pair',
    layout: 'custom',
    points: [
      P(0.2, 0.1),
      P(0.8, 0.1),
      P(0.5, 0.36),
      P(0.5, 0.6),
      P(0.5, 0.86),
      P(0.1, 0.48),
      P(0.9, 0.48),
    ],
    edges: [
      [0, 2],
      [1, 2],
      [2, 3],
      [3, 4],
    ],
    decoy: [5, 6],
    types: { 2: { type: 'merger' }, 5: { type: 'bomb' }, 6: { type: 'bomb' } },
    fakeEdges: [
      [5, 2],
      [2, 6],
    ],
    fakes: [{ x: 0.5, y: 0.48 }],
    starts: [0, 1],
    maxMistakes: 1,
    maxTaps: 2,
    timeLimit: 2.5,
    par: 4,
    hints: [
      'Merge needs both top starts.',
      'Side bombs and grey centre are bait.',
      'Tap both top links.',
    ],
  },
  {
    name: 'Taxed Branches',
    layout: 'tree',
    types: {
      1: { type: 'splitter' },
      2: { type: 'delay', delayMs: 1300 },
      3: { type: 'delay', delayMs: 900 },
    },
    fakeEdges: [
      [0, 5],
      [0, 4],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 3.8,
    par: 6,
    hints: [
      'Both branches delay - left more.',
      'Fake skips to tips change nothing.',
      'Tap top early.',
    ],
  },
  {
    name: 'Blast Into Merge',
    layout: 'custom',
    points: [
      P(0.5, 0.08),
      P(0.2, 0.38),
      P(0.8, 0.38),
      P(0.5, 0.62),
      P(0.5, 0.88),
      P(0.5, 0.38),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 3],
      [3, 4],
    ],
    decoy: [5],
    types: {
      0: { type: 'explosive', radius: 0.34 },
      3: { type: 'merger' },
      5: { type: 'bomb' },
    },
    fakeEdges: [
      [0, 5],
      [5, 3],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 2.8,
    par: 4,
    hints: [
      'Blast lights both arms into the merge.',
      'Centre bomb is fake-wired only.',
      'One tap: top.',
    ],
  },
  {
    name: 'Hidden Weave',
    layout: 'custom',
    points: [
      P(0.5, 0.04),
      P(0.16, 0.26),
      P(0.84, 0.26),
      P(0.5, 0.46),
      P(0.16, 0.7),
      P(0.84, 0.7),
      P(0.5, 0.9),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [3, 4],
      [3, 5],
      [4, 6],
      [5, 6],
    ],
    types: { 0: { type: 'splitter' }, 3: { type: 'merger' }, 6: { type: 'merger' } },
    hiddenEdges: [[2, 3]],
    fakeEdges: [
      [1, 5],
      [2, 4],
      [0, 6],
    ],
    starts: [0],
    maxMistakes: 1,
    timeLimit: 4,
    par: 7,
    hints: [
      'Right arm into the first merge is hidden.',
      'Cross weave lines are fake.',
      'Tap top.',
    ],
  },
  {
    name: 'Triple Crown',
    layout: 'custom',
    points: [
      P(0.1, 0.1),
      P(0.5, 0.08),
      P(0.9, 0.1),
      P(0.5, 0.4),
      P(0.5, 0.66),
      P(0.5, 0.9),
      P(0.28, 0.26),
      P(0.72, 0.26),
    ],
    edges: [
      [0, 3],
      [1, 3],
      [2, 3],
      [3, 4],
      [4, 5],
    ],
    decoy: [6, 7],
    types: { 3: { type: 'merger' }, 6: { type: 'bomb' }, 7: { type: 'bomb' } },
    fakeEdges: [
      [6, 3],
      [7, 3],
      [0, 6],
    ],
    starts: [0, 1, 2],
    maxMistakes: 1,
    maxTaps: 3,
    timeLimit: 2.6,
    par: 5,
    hints: [
      'Three top feeds - ignore bomb shoulders.',
      'Three taps, 2.6 seconds.',
      'Tap TL, top-middle, TR.',
    ],
  },
  {
    name: 'Merge Then Split',
    layout: 'custom',
    points: [
      P(0.1, 0.16),
      P(0.1, 0.5),
      P(0.36, 0.34),
      P(0.62, 0.34),
      P(0.9, 0.16),
      P(0.9, 0.5),
      P(0.62, 0.68),
      P(0.36, 0.86),
      P(0.5, 0.1),
    ],
    edges: [
      [0, 2],
      [1, 2],
      [2, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [6, 7],
    ],
    decoy: [8],
    types: { 2: { type: 'merger' }, 3: { type: 'splitter' }, 8: { type: 'bomb' } },
    fakeEdges: [
      [8, 2],
      [3, 8],
      [0, 8],
    ],
    starts: [0, 1],
    maxMistakes: 1,
    maxTaps: 2,
    timeLimit: 3,
    par: 6,
    hints: [
      'Merge left, then split three ways.',
      'Top bomb is fake-only.',
      'Tap both left starts.',
    ],
  },
  {
    name: 'Split & Merge - Final',
    layout: 'custom',
    points: [
      P(0.5, 0.04),
      P(0.18, 0.2),
      P(0.82, 0.2),
      P(0.5, 0.36),
      P(0.12, 0.56),
      P(0.5, 0.56),
      P(0.88, 0.56),
      P(0.5, 0.76),
      P(0.5, 0.94),
      P(0.3, 0.7),
    ],
    edges: [
      [0, 1],
      [0, 2],
      [1, 3],
      [2, 3],
      [3, 4],
      [3, 5],
      [3, 6],
      [4, 7],
      [5, 7],
      [6, 7],
      [7, 8],
    ],
    decoy: [9],
    types: {
      0: { type: 'splitter' },
      3: { type: 'merger' },
      5: { type: 'delay', delayMs: 1100 },
      7: { type: 'merger' },
      8: { type: 'timer', before: 3.8 },
      9: { type: 'bomb' },
    },
    fakeEdges: [
      [0, 8],
      [3, 9],
      [9, 7],
      [0, 7],
    ],
    starts: [0],
    maxMistakes: 1,
    maxTaps: 1,
    timeLimit: 4.2,
    par: 8,
    intro: 'Split, merge, wide split, delayed middle, merge, beat the tip timer.',
    hints: [
      'Trace top to bottom; skip bomb detours.',
      'Middle delay still feeds the lower merge.',
      'One tap on the crown, immediately.',
    ],
  },
];
