// Downloads the latin subset of the two display faces into public/fonts so the
// game renders identically with no network - and makes no third-party request
// at runtime, which keeps the Play data-safety answers honest.
// Both faces are variable fonts, so one file covers every weight.
// Run: node scripts/fetch-fonts.mjs
import { mkdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const QUERY =
  'https://fonts.googleapis.com/css2?family=Baloo+2:wght@500;600;700;800&family=Inter:wght@400;500;600;700&display=swap';
// Google serves woff2 variable fonts only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const SLUG = { 'Baloo 2': 'baloo-2', Inter: 'inter' };

const css = await fetch(QUERY, { headers: { 'User-Agent': UA } }).then((r) => r.text());

const faces = new Map(); // family -> { url, weights:Set }
for (const block of css.split('@font-face').slice(1)) {
  const family = /font-family: '([^']+)'/.exec(block)?.[1];
  const weight = /font-weight: (\d+)/.exec(block)?.[1];
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
  const range = /unicode-range: ([^;]+);/.exec(block)?.[1];
  // Keep the latin subset only; it is the block that starts at U+0000-00FF.
  if (!family || !weight || !url || !range?.startsWith('U+0000-00FF')) continue;
  const entry = faces.get(family) ?? { urls: new Set(), weights: new Set() };
  entry.urls.add(url);
  entry.weights.add(Number(weight));
  faces.set(family, entry);
}

mkdirSync('public/fonts', { recursive: true });
const rules = [];
let total = 0;

for (const [family, { urls, weights }] of faces) {
  const seen = new Map(); // content hash -> filename
  for (const url of urls) {
    const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
    const hash = createHash('sha1').update(bytes).digest('hex');
    if (seen.has(hash)) continue; // variable font: every weight is one file
    const name = `${SLUG[family] ?? family.toLowerCase()}-var.woff2`;
    writeFileSync(`public/fonts/${name}`, bytes);
    seen.set(hash, name);
    total += bytes.length;
    console.log(`  ${name}  ${(bytes.length / 1024).toFixed(1)} KB`);
  }
  const lo = Math.min(...weights);
  const hi = Math.max(...weights);
  for (const name of new Set(seen.values())) {
    rules.push(`@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${lo} ${hi};
  font-display: swap;
  src: url('./${name}') format('woff2-variations'), url('./${name}') format('woff2');
}`);
  }
}

writeFileSync(
  'public/fonts/fonts.css',
  `/* Self-hosted latin subsets - generated by scripts/fetch-fonts.mjs.
   Baloo 2 and Inter are licensed under the SIL Open Font License 1.1. */\n\n${rules.join('\n\n')}\n`,
);
console.log(`${(total / 1024).toFixed(1)} KB total -> public/fonts/`);
